### ISSUE TITLE
Cursor is not visible when navigating over icons in selection mode

### ISSUE THREAD

**Issue by snilek** [shimmerproject/Greybird#101]
While navigating over individual icons in selection mode (like over files or directories in file managers) using keyboard only, the actual cursor position is not marked in any way. This in effect complicates the process of item selection.

Steps to replicate:
Open a file-manager (like Thunar) in an icon mode. Select an item using arrow keys. Then hold down CTRL and try to select another item.

What is the result:
The cursor position is not indicated when navigating over other icons/items.
![thunar-greybird-as-is](https://cloud.githubusercontent.com/assets/7080806/9112061/945e2c6c-3c4c-11e5-8e5a-0d0eba017be9.png)

What should be the result:
The cursor position should be made visible (e.g. via a dotted frame around a file-name). Like so:
![thunar-greybird-as-it-should-be](https://cloud.githubusercontent.com/assets/7080806/9112064/96bb4544-3c4c-11e5-84bd-0ac92bde0678.png)

Thanks, best regards,
Jan Jansky

**Comment by ochosi** [comment]
Hadn't noticed, fixed in master.
