### ISSUE TITLE
Greybird crashes xfce4-panel when unusual caracter in window title: cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy

### ISSUE THREAD

**Issue by BlutHirnSchranke** [shimmerproject/Greybird#106]
I'm experiencing a wierd bug when using the greybird theme on my install of Arch Linux: When a window title contains unusual caracters like japanese or the play symbol (▶) the xfce4-panel (with the windowlist-plugin) crashes with the following error:

xfce4-panel: cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Zusicherung »!scaled_font->cache_frozen« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

While this can be fixed by installing the right font package (which fixes the problem for my at least for the crash with the japanese caracters, however I could not find out which font package is required for the play symbol) I consider this as a bug in the Greybird theme because it only happenes when using this theme. When using any other theme (including i.e. Bluebird) the panel behaves as expected and shows the caracters without problems. I also found a thread on the Arch Linux BBS which hints that I'm not the only one having this problem: https://bbs.archlinux.org/viewtopic.php?id=200186

**Comment by ochosi** [comment]
I have no idea how this could be related to the theme. It's likely a bug in the murrine engine and some setting in Greybird triggers it while Bluebird doesn't.

Either way, Murrine is unmaintained so there are little chances of ever getting a fix for this. I know this might be frustrating for you, but it seems like a wontfix to me.

**Comment by jazztickets** [comment]
@BlutHirnSchranke So as a workaround you can just comment out the `engine "murrine" {}` blocks inside gtk-2.0/apps/xfce-panel.rc

That fixed it for me.

**Comment by vbrandl** [comment]
I don't want to reopen another issue for this but the bug happens if a character is rendered that no installed font contains. If a font for that character is installed, it won't crash.
On the other hand, since murrine is unmaintined, maybe you should think about switching to another engine

**Comment by ochosi** [comment]
@vbrandl There are no on-par engines for Gtk2. The only way to go is to port all of Xfce over to Gtk3 (to which I'm contributing), but that'll take a while longer...
