### ISSUE TITLE
after update to gtk3-3.18: no space between icons and text in nautilus sidebar

### ISSUE THREAD

**Issue by dajuno** [shimmerproject/Greybird#109]
Hi, after updating gtk3, gnome-desktop and nautilus to 3.18, the nautilus sidebar looks weird with the Greybird theme.

Before (3.16): https://i.imgur.com/c34sX7M.png
After (3.18): https://i.imgur.com/UYVujbK.png

This did not happen with other themes, e.g., Adwaita for gnome 3.18: https://i.imgur.com/imDzr0F.png

Cheers

**Comment by ochosi** [comment]
I guess upstream changed the sidebar style. I'm still on Gtk3.16 and it'll take some time until I upgrade, so if you come up with a (ideally: backward compatible) way to fix this that would be great!

**Comment by dajuno** [comment]
Here they got the same problem.
https://github.com/shimmerproject/Numix/issues/256
https://github.com/shimmerproject/Numix/pull/264

**Comment by flandolfi** [comment]
I proposed a fix for this issue here shimmerproject/Numix#264. I added 

     .sidebar-icon {
           padding-left: $spacing;
           padding-right: $spacing;
     }

to the file `_nautilus.scss` (check "Files Changed" in  the previous link). If you wuold, try this patch and let me know if it solves this bug!

**Comment by dajuno** [comment]
I would, but this file doesn't exist.

https://github.com/shimmerproject/Greybird/tree/master/gtk-3.0

**Comment by flandolfi** [comment]
I see, Greybird theme files are different from Numix's. Try modifying `gtk-3.0/apps/gnome-applications.css` instead: add

    NautilusWindow .sidebar-icon {
        padding-left: $spacing;
        padding-right: $spacing;
    }

near line 135! :)

**Comment by dajuno** [comment]
yes, just figured this out (edit above). thanks :)
$spacing doesn't exist here, so the pixels need to be specified.

**Comment by flandolfi** [comment]
Oops, I noticed it too late! ..Does it work?

**Comment by flandolfi** [comment]
Ps. I think `5px` or `10px` should do the job ;)

**Comment by dajuno** [comment]
Yes, it does! I took 10px, that's fine. And compatible with gtk 3.16.
