### ISSUE TITLE
Radio buttons and check-boxes are not properly visible in Popover (Gtk-3.16, 3.18)

### ISSUE THREAD

**Issue by khurshid-alam** [shimmerproject/Greybird#112]
I am using Greybird from master in Ubuntu Wily. As shown in the following image, Radio buttons and check-boxes are not properly visible in popover. Same issue exists with Numix too.

![screenshot from 2015-11-14 00-25-03](http://i.imgur.com/f4vVcyA.png)

**Comment by ochosi** [comment]
This might be a problem with RTL languages, because the indicator is then very far away from the selected item (as seen in your scenario). I'm not sure I can enforce this behaviour in the theme, I'll have to look into that.

For LTR languages it definitely looks okay.

**Comment by ochosi** [comment]
As Greybird has been rebased on Adwaita for Gtk3.20 I won't be fixing issues for earlier Gtk3 releases anymore (unless they are totally easy and obvious), so this issue will be closed for now.

If you experience the same problem in Gtk3.20 please reopen it.
