### ISSUE TITLE
GTK 3.16: Class "sidebar" on widget cut GtkTreeView. Eg. GtkPlacesSidebar

### ISSUE THREAD

**Issue by matiasdelellis** [shimmerproject/Greybird#113]
Hi,
Two captures to you understand the problem...
GtkPlacesSidebar has the class "sidebar" in the parent widget.. and  cut her child GtkTreeView..

![sidebarclass0](https://cloud.githubusercontent.com/assets/733715/11288013/e7c7a27a-8efe-11e5-946a-ddf516ce887d.png)

If remove the class is shown correctly..

![sidebarclass1](https://cloud.githubusercontent.com/assets/733715/11288074/53005438-8eff-11e5-9b43-15e02a77879e.png)

**Comment by matiasdelellis** [comment]
p.s: This is reproducible in gtk 3.14 and 3.16..

Also just discovered that introducing the class to GtkTreeView instead of GtkPlacesSidebar, fix the problem. Of course this is not something you can change, but it may be useful to try.. :wink: 

![sidebarclass2](https://cloud.githubusercontent.com/assets/733715/11288167/2a05f38e-8f00-11e5-9614-b70398a62790.png)

**Comment by hungrywolf27** [comment]
I am experiencing this issue on Xubuntu 16.04 (GTK 3.18). Through trial and error, I've figured out that the problem goes away when [this single line of code](https://github.com/shimmerproject/Greybird/blob/15fdec94c8fd1c72454488085396d2d0911d70cf/gtk-3.0/gtk-widgets.css#L2130) is commented out, for reasons I don't understand.

Here is the GTK3 file chooser (from Mousepad). Notice that in the left sidebar panel, only when the scrollbar is showing, there are thick borders of "empty space" cutting off the top and bottom:
![image](https://cloud.githubusercontent.com/assets/8271455/15809141/b4b61858-2b57-11e6-8f80-1da00d3adbc2.png)

After commenting out the ```background-color``` line and reloading the theme, here is the sidebar displaying properly:
![image](https://cloud.githubusercontent.com/assets/8271455/15809140/a4d7fa82-2b57-11e6-9d54-6245eb72fc59.png)

I do not see this problem with other themes, only Greybird.

**Comment by ochosi** [comment]
Sorry I hadn't noticed this earlier, it should be fixed in master now.
