### ISSUE TITLE
GNOME-style applications have a weird border around their window decorations

### ISSUE THREAD

**Issue by szabba** [shimmerproject/Greybird#115]
![2016-01-15-205730_1366x768_scrot](https://cloud.githubusercontent.com/assets/820119/12363746/c1fa0bde-bbca-11e5-8a2f-74fa60e8886f.png)

I hope it's visible enough.

**Comment by ochosi** [comment]
That's not a bug, but since you haven't enabled compositing in Xfwm4 all Gtk+3 apps that use headerbars (what you called Gnome-Style decorations) have square borders, nothing I can do about that.

**Comment by szabba** [comment]
Thanks, good to know.
