### ISSUE TITLE
Broken scrollbars in webkitgtk (WebKitWebView)

### ISSUE THREAD

**Issue by hrnr** [shimmerproject/Greybird#118]
Webkit changed style hadling since 2.10.5. It breaks Greybird theming for scrollbars (scrollbars are rendered directly by webview they are not a gtk elements).

Here I show the issue in devhelp, but it affects all application using webview.

![screenshot broken](https://cloud.githubusercontent.com/assets/1316311/12719217/0c8389ec-c8f4-11e5-9174-b0b62ba33e2d.png)

I tried to fix this issue in my [branch](https://github.com/hrnr/Greybird/tree/scrollbars). It looks better (at least it is usable), but still different than before.

![screenshot partialy fixed](https://cloud.githubusercontent.com/assets/1316311/12719200/f4b4f9b8-c8f3-11e5-827a-bc1cba762359.png)

With Adwaita everything looks just fine.

**Comment by hrnr** [comment]
I has been fixed now, either by webkit or by latest commits.

**Comment by ochosi** [comment]
Ok, thanks for the notice!
