### ISSUE TITLE
Gtk2 scrollbar when windows maximize

### ISSUE THREAD

**Issue by arshavindn** [shimmerproject/Greybird#121]
when windows in maximize mode, it's easy to move cursor to the extreme right and drag slider but this theme does not support it

**Comment by ochosi** [comment]
Yup, I'm aware of that and it's a design decision, so a wontfix.

**Comment by arshavindn** [comment]
it's kinda odd, every theme can do that. I think user can feel free to reach slider and drag it, instead of being careful to move cursor right to slider

**Comment by ochosi** [comment]
Yeah, as long as you don't want rounded corners for the slider and padding inside the scrollbar's trough. But as those are the design decisions, it is what it is.

It's fairly easy to change that though for yourself if you dislike the current style, just change the GtkScrollbar trough-border to 0 in gtk-2.0/gtkrc and GtkRange-trough-border: 3 to 0 in gtk-3.0/gtk-widgets.css
