### ISSUE TITLE
Nemo path

### ISSUE THREAD

**Issue by arshavindn** [shimmerproject/Greybird#122]
Just like the picture, the issue is buttons in middle of the path
![documents_051](https://cloud.githubusercontent.com/assets/10246162/13975235/cb88f318-f0e5-11e5-9293-119e7d7aced1.png)

**Comment by ochosi** [comment]
What version of Greybird and Gtk3 is that?

**Comment by arshavindn** [comment]
the lastest version of greybird pulling from git and i'm using gtk 3.18

**Comment by ochosi** [comment]
Strange, I thought I fixed all issues with linked buttons, but it's possible that I didn't. I'll see whether I can install nemo and reproduce this.

**Comment by ochosi** [comment]
I can meanwhile reproduce the issue, I'll see when I get some time to fix it (can't promise anything though, fairly busy atm).

**Comment by ochosi** [comment]
The issue should be less bad in Gtk3.18 with the last release and finally fixed in the gtk3.20 branch.

**Comment by ochosi** [comment]
As the gtk3.20 branch was merged and released I'm closing this issue
