### ISSUE TITLE
dialog box buttons: bottom borders missing and too little spacing in between

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#127]
I currently use the latest Greybird from official Ubuntu 16.04 repositories and this is the biggest issue I've encountered so far.

![screenshot from 2016-05-02 12-59-51](https://cloud.githubusercontent.com/assets/6375934/14952257/9b389802-1067-11e6-811c-5b70ba957437.png)

Is it possible please to make those **bottom borders visible** and add **a little more spacing** between buttons?

If I may, I would also like to ask why I see such buttons sometimes "fully justified" (covering the bottom area of the dialog box from left to right) and sometimes like this; is it because Ubuntu has a mix of different GTK3 versions leading to such an inconsistent behavior?

**Comment by ochosi** [comment]
Yes, I would say the inconsistency with respect to the button widths is because of different widgets, some use the GtkButtonBox, others use something else...

Where does that dialog come from? (Can't seem to be able to find one)

**Comment by Sadi58** [comment]
I know you don't use Unity (fortunately this great-looking theme does support it) and probably that's why you don't see that dialog, because it pops up in Nautilus (actually in one or two others as well).

**Comment by raginggoblin** [comment]
This is indeed happening for all Nautilus dialogs. The above example is the confirm box when you try to delete an item. But it also happens e.g. when you right click to compress a folder or a set of files using file-roller plugin of Nautilus.

**Comment by ochosi** [comment]
Does this still happen with the gtk3.20 branch and Nautilus 3.20?

**Comment by raginggoblin** [comment]
How can I test that? I have Ubuntu 16.04 which is the newest version but uses gtk 3.18

**Comment by jbicha** [comment]
You could boot an Ubuntu 16.10 alpha image, and install greybird-gtk-theme from the repositories.
http://cdimage.ubuntu.com/daily-live/current/

**Comment by raginggoblin** [comment]
![screenshot from 2016-08-10 20-50-47](https://cloud.githubusercontent.com/assets/1873470/17566549/331a77bc-5f3c-11e6-9cae-4653fe405ee7.png)

**Comment by jbicha** [comment]
From the Live image, I opened software-properties-gtk and enabled Community-maintained free and open-source software (universe). After it reloaded sources, I ran
```
sudo apt install greybird-gtk-theme
gsettings set org.gnome.desktop.interface gtk-theme Greybird
```

Your screenshot shows what I would expect to see if you were trying to run a GTK 3.18 theme with GTK 3.20 but that shouldn't happen with the greybird-gtk-theme in the Ubuntu 16.10 repositories.

**Comment by raginggoblin** [comment]
@jbicha I downloaded the one from github, but using your method the result looks like this:
![screenshot from 2016-08-10 21-38-39](https://cloud.githubusercontent.com/assets/1873470/17568232/2e1a5438-5f43-11e6-9ae8-2da7ce9a1dba.png)

**Comment by ochosi** [comment]
So it's fixed..?

**Comment by jbicha** [comment]
@raginggoblin You can trigger a similar dialog to your original bug report with Shift+Delete.

**Comment by raginggoblin** [comment]
Yes, I checked that one too and it seems resolved to me. Good work! Only thing is, the corners are now square instead of rounded. Is that intentional?

**Comment by ochosi** [comment]
The corners of what, the window decorations? If so, I didn't touch those at all.

**Comment by raginggoblin** [comment]
Yes, I meant the window decorations.

**Comment by ochosi** [comment]
Right. As I use neither metacity/mutter nor compiz I'm clueless as to what could be broken there. It's a different issue altogether though, so if you could open a separate issue that'd be great. I'm closing this one now.

**Comment by raginggoblin** [comment]
Will do. I must say I feel sorry for you man. These gtk breaking changes would drive me mad.
