### ISSUE TITLE
GTK3.20: Nautilus statusbar needs opaque background

### ISSUE THREAD

**Issue by jbicha** [shimmerproject/Greybird#134]
The hovering statusbar at the bottom of Nautilus has a transparent background which is a problem when it overlaps content.

Adwaita and Numix 2.6.1 are two themes I found that don't have the transparent background issue.

![greybird-with-nautilus-320](https://cloud.githubusercontent.com/assets/876259/17106355/0ca879d4-5259-11e6-8c83-427b83260f49.png)

(Please ignore the privacy pixelated sidebar.)

- greybird-gtk-theme [3.18.0+20160720.7b72fea.gtk320-1](https://launchpad.net/ubuntu/+source/greybird-gtk-theme/3.18.0+20160720.7b72fea.gtk320-1) (from your gtk3.20 git branch)
- Nautilus 1:3.20.1-3ubuntu1~xenial1 from the [GNOME3 Staging PPA](https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging/) although if you're using Yakkety, the Ubuntu Desktop [GTK3.20 PPA](https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/gtk320/) has a similar version if you don't want to update as many packages on your computer
- Ubuntu GNOME 16.10 "yakkety"

**Comment by ochosi** [comment]
May I ask - just for reference - what version of Adwaita/Gtk3.20 exactly? Just FYI, Greybird is based on Adwaita 3.20.6 (which was the newest release at the time of rebasing).

**Comment by jbicha** [comment]
- gtk+3.0 3.20.6-2ubuntu1~xenial2
- gnome-themes-standard 3.20.2-1ubuntu1~xenial1

Both from the Staging PPA

**Comment by ochosi** [comment]
Very odd, I can reproduce the issue. Not sure though as to what widget that actually is.

**Comment by ochosi** [comment]
Ok, so I've figured out how to theme it correctly, but my .view class in Nautilus still differs from when using Adwaita and I'm really unsure what's going on there - maybe there's some Nautilus-specific theming going on somehow somewhere..?

Anyway, for reference, the .floating-bar class is currently unthemed. Adding this to _common.scss should fix it (if you wanna try):

/*****************
 * Floating bars *
 *****************/
.floating-bar {
    background-color: $base_color;
    border-style: solid;
    border-color: $borders_color;
    &:left {
        border-radius: 0 3px 0 0;
        border-width: 1px 1px 0 0;
    }
    &:right {
        border-radius: 3px 0 0 0;
        border-width: 1px 0 0 1px;
    }
}

But before I push this, I really wanna find out where that theming part is hidden in Adwaita.

**Comment by jbicha** [comment]
I added those lines to the bottom of my gtk-3.0/_common.scss but it didn't seem to help here.

Did you test with the Debian/Ubuntu package or did you build/install it yourself? Like I mentioned in #135, the Debian package doesn't currently run the parse-sass script, but I don't know how important that step is.

**Comment by ochosi** [comment]
Did you run the parse-sass script after adding to the scss? If not, that snippet cannot work

**Comment by jbicha** [comment]
Ok, yes the snippet works. Thanks.

**Comment by morgoth6** [comment]
I think there is a typo i proposed patch. It should be

-- &:left {
++ &.left {

And

-- &:right {
++ &.right {

**Comment by ochosi** [comment]
@morgoth6 Indeed, a typo. Either way, I'll include more complete nautilus theming in the release, so hang in there a little longer ;)

**Comment by ochosi** [comment]
Should be fixed now in the gtk3.20 branch, please reopen if you still encounter this bug!
