### ISSUE TITLE
GTK 3.20: small scrollbars barely visible

### ISSUE THREAD

**Issue by rohieb** [shimmerproject/Greybird#137]
It's great that I can now use Greybird with GTK 3.20 :-) I'm using the theme through the [Debian package](http://packages.debian.org/greybird-gtk-theme), which is built from commit `7b72fea` of the `gtk-3.20` branch. The small scrollbars on my GTK 3 apps (when they're not being hovered upon) look good with Adwaita:
![gedit with Adwaita](https://gist.githubusercontent.com/rohieb/06eb8a0df366fc99cdf7bd66a6f925c3/raw/1fd24a3b63d2a1aefed8393856ec7e3f968a0111/3cee0a04-5c5f-11e6-886a-b37dcaa31849.png)

However with Greybird, they are only faintly visible:
![](https://gist.github.com/rohieb/06eb8a0df366fc99cdf7bd66a6f925c3/raw/1fd24a3b63d2a1aefed8393856ec7e3f968a0111/fd624564-5c5c-11e6-8b8e-73992b7b060a.png)

This is especially troubling when there is content to be scrolled in the direction of the toolbar, so these little "continuation lines" are drawn at the border (like a PDF in evince that is bigger than the window) . In this case, the scrollbars are virtually invisible:
![](https://gist.github.com/rohieb/06eb8a0df366fc99cdf7bd66a6f925c3/raw/1fd24a3b63d2a1aefed8393856ec7e3f968a0111/e26bab76-5c5a-11e6-8fbb-2bbe99642745.png)

Unfortunately I was not able to debug the problem with GtkInspector. Could it be that some opacity is applied to the scrollbar multiple times?

**Comment by ochosi** [comment]
Thanks for noticing, should be fixed now (please reopen if not).

**Comment by rohieb** [comment]
Much better, thanks a lot!
