### ISSUE TITLE
Invisible toggles in GTK3.20 branch

### ISSUE THREAD

**Issue by morgoth6** [shimmerproject/Greybird#138]
Some checkboxes are rendered as same for checked and unchecked state. Can be seen for example in yumex-dnf or system-config-prnter. Tested with 06bd49a58f419f65e95bf49cae8ba0dec1732942 on Fedora 24 system.

In both attached grabs some of the checkboxes are checked and some unchecked, but looks the same.

![screenshot_2016-08-07_16-37-32](https://cloud.githubusercontent.com/assets/4990118/17463018/c7322138-5cbd-11e6-84fc-1270f22708d1.png)

![screenshot_2016-08-07_16-38-30](https://cloud.githubusercontent.com/assets/4990118/17463019/cd82a864-5cbd-11e6-8fd2-ad6e187a6a62.png)

**Comment by ochosi** [comment]
Interesting.. I presume this works with Adwaita?

**Comment by morgoth6** [comment]
Yes it looks fine. Regular checkboxes looks fine in both themes only this "toggles" produce problems. Not sure about the real name, but in GtkInspector the object in defined as  GtkCellRendererToggle if I remember correctly.

![screenshot_2016-08-08_09-58-25](https://cloud.githubusercontent.com/assets/4990118/17473136/1c4feec0-5d4f-11e6-856a-b087dca0c18d.png)

**Comment by ochosi** [comment]
I can reproduce the issue now, I'll look into fixing it.

**Comment by ochosi** [comment]
Definitely a very strange issue. If I put the code for check:checked into inspector the checkbox looks fine :/

**Comment by ochosi** [comment]
Right, so currently all checkboxes and radios seem to be broken...
 
When bisecting this issue it seems like it was introduced with 3b29a2a7f6ba11705abbff7c9bd0f3bbf382f3cc, not sure how you could run into it with commit https://github.com/shimmerproject/Greybird/commit/06bd49a58f419f65e95bf49cae8ba0dec1732942 when that one isn't on the gtk3.20 branch at all...

So basically what I conclude is that the gtkresource magic that @jbicha added doesn't work and consequently the svg/png assets aren't loaded for checkboxes and radios. I'll try to either fix the gtkresource approach or revert it.

**Comment by ochosi** [comment]
Would be nice if @morgoth6 could confirm that things are still ok before https://github.com/shimmerproject/Greybird/commit/3b29a2a7f6ba11705abbff7c9bd0f3bbf382f3cc

**Comment by jbicha** [comment]
@ochosi Yes, the toggles work fine before the gtkresource switch (like in the Ubuntu yakkety package).

You can commit [this](https://github.com/jbicha/Greybird/commit/756a7275ee77e0fb160da8806313f00031245959) if you want so that this doesn't block a 3.20 release.

**Comment by morgoth6** [comment]
I pull current revision 2ba90a0ee9bd5691267733b4ca43f21ca162e680 and apply a simple patch.
```
diff -urN greybird-org/gtk-3.0/gtk.css greybird-06bd49a58f419f65e95bf49cae8ba0dec1732942/gtk-3.0/gtk.css
--- greybird-org/gtk-3.0/gtk.css	2016-08-09 22:47:50.000000000 +0200
+++ greybird-06bd49a58f419f65e95bf49cae8ba0dec1732942/gtk-3.0/gtk.css	2016-08-10 09:45:31.167919204 +0200
@@ -1 +1 @@
-@import url("resource:///org/shimmerproject/greybird/gtk-3.0/gtk-contained.css");
+@import url("gtk-contained.css");
```
And I can confirm the toggles are visible again.

**Comment by ochosi** [comment]
Alright, reverted the gtkresource switch. We can always do that in a later release, for now I want to get a first stable 3.20 release out.
@jbicha Thanks again!
