### ISSUE TITLE
Window decorations have square corners

### ISSUE THREAD

**Issue by raginggoblin** [shimmerproject/Greybird#139]
On Ubuntu 16.10 (gtk 3.20) the corners of window decorations look square instead of rounded.
![screenshot from 2016-08-10 22-03-05](https://cloud.githubusercontent.com/assets/1873470/17568943/534ddba0-5f46-11e6-9cd8-aef2e96734da.png)

**Comment by ochosi** [comment]
Just to be sure, which window decorator are you using with compiz?

**Comment by raginggoblin** [comment]
Default one, unity decorations.
https://wiki.ubuntu.com/Unity/Theming

**Comment by ochosi** [comment]
Yeah, sorry, I meanwhile realized that I haven't ported over the unity.css and that this is needed for the window decorations (and the panel btw). So I'll do now.

**Comment by ochosi** [comment]
@raginggoblin Alright, pushed it. Please test and let me know!
(I don't have Unity, but the changes are based on the changes made to the Ubuntu themes for 16.10.)

**Comment by raginggoblin** [comment]
I am really trying to test it but I struggle how to do it properly. Using the themes from the repos on Ubuntu 16.10 it looks fine. But when I download this theme from github and move the contents of the zip to /usr/share/themes/ it somehow looks awful:
![screenshot from 2016-08-13 16-51-27](https://cloud.githubusercontent.com/assets/1873470/17643866/a6017622-6176-11e6-813d-48617341e8d0.png)

**Comment by ochosi** [comment]
Are you using the correct branch..?

**Comment by raginggoblin** [comment]
Looks great! Thanks for this fabulous theme!
![screenshot from 2016-08-15 19-35-07](https://cloud.githubusercontent.com/assets/1873470/17673063/b3d1e53e-631f-11e6-8c62-e089e8ff5154.png)
