### ISSUE TITLE
error ./gtk-3.0/gtk-contained.scss (Line 16: File to import not found or unreadable: unity.

### ISSUE THREAD

**Issue by carno** [shimmerproject/Greybird#141]
With latest master content I get the following error when trying to _compile_ the theme:
```bash
$ LANG=C make
rm -rf ./gtk-3.0/.sass-cache
test -z "gtk-3.0/gtk.gresource gtk-3.0/gtk-contained.css gtk-3.0/gtk-contained-dark.css" || rm -f gtk-3.0/gtk.gresource gtk-3.0/gtk-contained.css gtk-3.0/gtk-contained-dark.css
sass --update --sourcemap=none ./gtk-3.0
      write ./gtk-3.0/gtk-contained-dark.css
      error ./gtk-3.0/gtk-contained.scss (Line 16: File to import not found or unreadable: unity.
Load path: /home/carno/dokumenty/github/Greybird/gtk-3.0)
Makefile:560: recipe for target 'compile' failed
make: *** [compile] Error 1
```

**Comment by carno** [comment]
With
```diff
diff --git a/gtk-3.0/gtk-contained.scss b/gtk-3.0/gtk-contained.scss
index e1ed31b..f732ac7 100644
--- a/gtk-3.0/gtk-contained.scss
+++ b/gtk-3.0/gtk-contained.scss
@@ -13,4 +13,4 @@ $variant: 'light';
 @import 'xfce';
 @import 'lightdm-gtk-greeter';
 @import 'gnome-apps';
-@import 'unity';
+// @import 'unity';
```
all goes well. Am I missing some dependency (those mentioned in the readme are installed, OS: Debian Sid)

BTW, would it be possible to disable some parts of the theme such as unity support for people not needing it on `configure` level?

**Comment by ochosi** [comment]
Indeed, for some reason the SASS file for Unity was left out, apparently I had forgotten to push it so your compilation problem should be fixed.

If you take the release tarball, there is no need to compile the theme, you can just use it. The compilation is for when you change stuff manually in SASS and want to get it compiled to CSS.

Yeah, those things could be made configurable through `configure` - feel free to play with that and submit a patch! ;)
