### ISSUE TITLE
transmission

### ISSUE THREAD

**Issue by mrpunkk** [shimmerproject/Greybird#145]
weird menu in transmission

gtk+3-3.18.9-x86_64-1 in slackware 14.2
![transmission2](https://cloud.githubusercontent.com/assets/21990293/18233509/cafc25d0-72bf-11e6-8ae7-44bbd616582f.png)
![transmission1](https://cloud.githubusercontent.com/assets/21990293/18233517/dbd76a18-72bf-11e6-8748-d3e2df65607e.png)

**Comment by ochosi** [comment]
That looks totally broken - are you using Gtk+3 in version >=3.20? (Hint: Xubuntu Xenial currently has Gtk 3.18)
Note that the last release only works with this version and above.

**Comment by jbicha** [comment]
> gtk+3-3.18.9-x86_64-1 in slackware 14.2

Please use Greybird 3.18.0. Greybird 3.20.0 (or git master) is only for GTK 3.20+

**Comment by ochosi** [comment]
Please reopen if you're sure this is a real issue.
