### ISSUE TITLE
Unnecessary scrollbars visible in Firefox

### ISSUE THREAD

**Issue by malysps** [shimmerproject/Greybird#146]
This issue is very minor and I spotted it on only one website (twitch.com) but it may occur on other. I'm using Xubuntu 16.04 and with default Greybird theme this particular website looks bad because of unnecessary scrollbars. I'll show it on two screen shots:

1) Zukitre theme, looks good.
http://prnt.sc/ceioxz

2) Greybird, you can see scrollbar on the left side (above avatar) and overlapping scrollbars on the right side (where the cursor is)
http://prnt.sc/ceio54

**Comment by ochosi** [comment]
This is quite odd. Obviously there's an additional (Javascript?) scrollbar added by twitch, no idea why it would work with one theme and not the other. I can also say that I'm not very inclined to investigate unless this happens on more than twitch.com...

**Comment by malysps** [comment]
I guess you can close this issue. I'm on Xubuntu 16.10 and all is OK now. Plus, I didn't saw it occurring on any other website.

**Comment by ochosi** [comment]
Ok, thanks for the update!
