### ISSUE TITLE
Awful dotted lines on borders

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#150]
Hi!

I've detected some awful behavior that appears when any data or information is out of the visible content zone in some applications.

![screenshot45](https://cloud.githubusercontent.com/assets/5833446/18789644/01bb96aa-81ac-11e6-9d28-36608d8e5bd6.png)

Some dotted lines appear near the borders and this does not look very well and this do not appear in GTK2 apps, so GTK2 and GTK3 behavior is different.

You can see them more clearly here:

![screenshot45b](https://cloud.githubusercontent.com/assets/5833446/18789661/13bedc5e-81ac-11e6-84b2-55d2a76bc46c.png)

It is possible to remove them?

Thanks for your great theme and your work! ;)

**Comment by PeterFeicht** [comment]
That's the GTK3 way of showing that there's something hidden that can be scrolled to. I rather like it, I think it should definitely stay that way.

**Comment by jEsuSdA** [comment]
I think these lines does not add any useful information, because the scrollbars still there.
IMHO,  while GTK3 puts these lines, GTK2 does not, so, the behavior between apps is different depends on the GTK version they use, and this breaks consistency. ;)

**Comment by PeterFeicht** [comment]
Don't the scroll bars disappear in GTK3 when the mouse doen't move?

**Comment by ochosi** [comment]
Whether the scrollbars are persistent or go away on inactivity (the latter is default) can be configured by setting an environment variable (e.g. Xubuntu disables the Gtk3 scrollbars disappearing). So anyway, this is impossible to get "right" for everyone to some extent, but I feel the lines rather add value than distract or visually disrupt the UI. So for now this is a "won't fix".

**Comment by jEsuSdA** [comment]
To whom who wanted to remove this awful lines, You can remove them editing  gtk-3.0/gtk-contained.css and write at the end of file this:

`scrolledwindow undershoot.top, scrolledwindow undershoot.right, scrolledwindow undershoot.bottom, scrolledwindow undershoot.left { background-image: none; }`

Cheers!

**Comment by hrqmonteiro** [comment]
> For those who wanted to remove this awful lines, You can remove them editing gtk-3.0/gtk-contained.css and writing at the end of file this:
> 
> `scrolledwindow undershoot.top, scrolledwindow undershoot.right, scrolledwindow undershoot.bottom, scrolledwindow undershoot.left { background-image: none; }`
> 
> Cheers!

I don't have a gtk-contained.css file, is this a problem?

**Comment by dagraver** [comment]
> > For those who wanted to remove this awful lines, You can remove them editing gtk-3.0/gtk-contained.css and writing at the end of file this:
> > `scrolledwindow undershoot.top, scrolledwindow undershoot.right, scrolledwindow undershoot.bottom, scrolledwindow undershoot.left { background-image: none; }`
> > Cheers!
> 
> I don't have a gtk-contained.css file, is this a problem? What should i do? I tried creating one and adding these lines and didn't work.

Put it in a file called '~/.config/gtk-3.0/gtk.css' and it should work.
