### ISSUE TITLE
Suggestion: Status bar drop-down list smaller and thiner

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#151]
Hi!

What do you think about status bar drop-down lists?
The new Greybird version draws a big ones that consumes a lot of space. I think it will be more elegant to do them smaller and thiner.

You can see here what I mean:

![screenshot45](https://cloud.githubusercontent.com/assets/5833446/18790173/0ab9d30a-81ae-11e6-9dc6-b606f9643ea3.png)

I like the Zukitre one.

What do you think about that?

**Comment by ochosi** [comment]
Using gedit they already seem quite slim to me. What version of Greybird is this? (Note that I slimmed down some widgets in the 3.20.1 release)
![gedit](https://cloud.githubusercontent.com/assets/261436/19008002/918bcbd0-8768-11e6-93e8-48faa177fb36.jpg)

**Comment by jEsuSdA** [comment]
Hi!

My screenshots are about PLUMA (the Mate desktop gedit fork):
https://github.com/mate-desktop/pluma

Thanks! ;)

**Comment by ochosi** [comment]
Hm, odd, well I'm not really keen on adding too much per-application theming as it is a pain to maintain (plus I don't use Mate).

**Comment by jEsuSdA** [comment]
Oh. I see and I understand this. ;)

But instead you don't use Mate, consider that mate apps are converted in desktop free apps (called XApps) and it's goal is to provide several common apps to be used in any desktop like XFCE and others.

Pluma -> Xed
EoG -> Xviewer
Atril -> Xreader
Totem -> Xplayer
Gthumb -> piX
...

You can see more information about that here:
https://www.linuxmint.com/rel_sarah_xfce_whatsnew.php

Thanks! ;)

**Comment by jbicha** [comment]
@jEsuSdA Could you check what version of greybird you have installed?

**Comment by jEsuSdA** [comment]
@jbicha , How can I check the version?

I've download the greybird files clicking on "CLONE OR DOWNLOAD" button the past 2016/09/23 day.

Thanks! ;)

**Comment by jbicha** [comment]
@jEsuSdA Thanks. That answers the question. Some distros package Greybird and, like was said earlier, 3.20.1 shrunk the padding but you apparently already have those changes.

**Comment by jEsuSdA** [comment]
You're welcome. 
I always download the git version to grantee it is the last one. ;)

Thanks!!!

**Comment by ochosi** [comment]
I meanwhile deflated more widgets, but to be honest I think the statusbar is proportional compared to the rest, so I'll close this one as wontfix.
