### ISSUE TITLE
Dark Checkbox background on GTK2 

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#152]
Hi!

The checkbox background in gtk2 apps is dark.

![screenshot45](https://cloud.githubusercontent.com/assets/5833446/18790602/b1176be4-81af-11e6-8e2f-17544f482684.png)

Could it be a theme bug or a GTK one?
Thanks! ;)

**Comment by ochosi** [comment]
Very, haven't seen that so far and can't really imagine it would be a glitch in Gtk2 as it hasn't changed for ages.
The murrine engine, which is responsible for drawing these ticks also hasn't been touched in years as far as I know.

Could you tell me more about your setup so I can try to reproduce?

**Comment by jEsuSdA** [comment]
Greybird -> latest, from github (I usually clic on "clone or download" button and download it).
gtk2-engines-murrine 0.98.1.1-6 (from Debian repositories)
libgtk 3 -> 3.22.0
libgtk 2 -> 2.24.30

I don't know if you need some other information. Please, let me know. ;)
Thank you!! ;)

**Comment by ochosi** [comment]
Could you try a different icon-theme? I don't see any other meaningful differences to my own setup... (only diff is murrine 0.98.2 in Ubuntu)

**Comment by jEsuSdA** [comment]
Hi, Ochosi. ;)

Greybird -> latest, from github
gtk2-engines-murrine 0.98.1.1-6 (from Debian repositories)
libgtk 3 -> 3.22.2-1
libgtk 2 -> 2.24.31

I've tested using Papirus and Faenza, and others and the dark checkboxes still remain.
But... I try to login with another user and the checkboxes are fine... so, it is caused a missconfiguration in my own account... but I don't know from where this background color is taken. :s

You can close this bug. ;)

Any suggestion about how I can solve this problem?

**Comment by ochosi** [comment]
Maybe you have a custom .gtkrc file in your home dir or in .config/gtk-2.0?

Anyway, closing the report.

**Comment by jEsuSdA** [comment]
I'm going to try to solve this. ;)
Thanks for your suggestion. ;)

**Comment by jEsuSdA** [comment]
I've solved.
Y deleted all the gtk configuration files, upgrade all packages and reconfigure all GTK themes, incons, etc. All appears to work now.

But I sadly discovered QT5 has remove the GTK+ theme support and now, the QT5 apps looks like so awful. Sometimes I think the QT and GTK race to nowhere in every single update is a stupid way to waste the theme designers time and the users patience. I hate them!

**Comment by gyll** [comment]
You need to install qt5-style-plugins (or whatever this package is called for your distro) and add "export QT_QPA_PLATFORMTHEME=gtk2" in your ~/.profile (or whichever startup file you have for your login shell), and then Qt5 apps will take the gtk style
