### ISSUE TITLE
Progress bar visual glitches GTK3

### ISSUE THREAD

**Issue by skontar** [shimmerproject/Greybird#153]
It seems that commit 1942afc8732f904a1139fd41d7afd74263b87887 which fixed zero size progress bars introduced visual glitches.

The ending of the "full" progress bar part is slightly different on the top and on the bottom, making skewed look. It is more apparent when color is changed (e.g. how xfce4-notifyd is now handled). 

Another glitch is visible when size of the progressbar is changed in application. This can be improved by setting "trough" and "progress" height differently, but I am not sure that application developers will expect those to be different.

The pictures are differences between 3.20.0 and 3.20.1 on my system.

![3 20 0](https://cloud.githubusercontent.com/assets/10827040/18987395/c5621f48-8701-11e6-8f1e-2e925aed6381.png) ![3 20 1](https://cloud.githubusercontent.com/assets/10827040/18987398/c5686c4a-8701-11e6-8bfb-9d95586be235.png)

![3 20 0x2](https://cloud.githubusercontent.com/assets/10827040/18987397/c563005c-8701-11e6-8cbe-01a42a77100e.png)

![3 20 1x2](https://cloud.githubusercontent.com/assets/10827040/18987396/c562f4d6-8701-11e6-9a0d-1e98c802e52c.png)

**Comment by ochosi** [comment]
I noticed this visual glitch when I was working on a fix and couldn't find a solution. It seems to be related to the border-radius, but changing that wouldn't help.

I'm open to suggestions (other than simply reverting the fix).

**Comment by skontar** [comment]
So I have looked at around 10 most popular GTK3 themes and only one of them did progressbar zero size correctly. That theme was the only one which did not have border for "progressbar progress". It looks to me that this needs to be fixed in GTK3 engine. GTK2 did not have this problem as far as I know.

**Comment by skontar** [comment]
I have also checked on Fedora 24 with Gnome desktop and default Adwaita theme. Still, zero progress progress bars show border.

**Comment by ochosi** [comment]
So which theme makes it work?

**Comment by skontar** [comment]
None, actually. There is no GTK3 theme I have seen which would do both 1) a border around progress part of progressbar, and 2) not show anything for 0% progress.

The one I was writing about is Dark-Aurora, but it does not have border for progress part of progressbar. Greybird looks quite ugly without it.

**Comment by skontar** [comment]
I kind of reminded myself that this was not an issue last time I wrote GTK3 application in Python, as I clearly remember having this issue in Qt only.

So I did some more digging. I have installed Fedora 22, 23, and 24 in VM and tried to check how empty progressbars look with Adwaita and Greybird supplied with those versions of OS:

Fedora 22
GTK 3.16.3
pyGObject 3.16.1
Empty progress bar works fine

Fedora 23
GTK 3.18.2
pyGObject 3.18.0
Empty progress bar works fine

Fedora 24
GTK 3.20.9
pyGObject 3.20.1
Empty progress shows border, e.g. is not completely empty

Maybe I do not understand something in here, but it looks like GTK 3.20 new bug / feature to me.

**Comment by ochosi** [comment]
After some discussions with the Gtk+ devs I came up with a patch that fixes the problem (let's hope it gets merged).
https://bugzilla.gnome.org/show_bug.cgi?id=774695

**Comment by skontar** [comment]
Awesome. Thanks!

**Comment by stefson** [comment]
I think it was merged a few months ago, so the issue can be closed?

**Comment by ochosi** [comment]
Indeed, this is done.
