### ISSUE TITLE
Unity 7.4 Ubuntu 16.04 Greybird installed from this repo looks broken

### ISSUE THREAD

**Issue by Feichtmeier** [shimmerproject/Greybird#156]
Sorry for this issue if it is (prbly is) my stupidity:

When I install Greybird from the official Ubuntu repos it looks as it should but when I install it from this repo I looks broken. I just wanted to check the newer versions here. Again sorry if this is just my stupidity feel free too delete this issue

![bildschirmfoto vom 2016-10-24 20-03-07](https://cloud.githubusercontent.com/assets/15329494/19657533/e8dca264-9a24-11e6-8858-22ff1aaafa14.png)

**Comment by ochosi** [comment]
If you pulled Git master then yes, this cannot work. Better use the releases shipped in the Ubuntu repos, as those have been tested for their respective Gtk3 versions.
You're obviously using Greybird 3.20.x which targets Ubuntu 16.10 so it can't work.
