### ISSUE TITLE
Unity titlebar problem

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#157]
Using the latest version in Ubuntu 16.10 repositories, there's a border problem between titlebar and toolbar in _some_ apps, e.g. nautilus, gedit, libreoffice and totem player (see the screenshot below) while other apps display a seamless transition as usual.
![screenshot from 2016-10-26 00-55-00](https://cloud.githubusercontent.com/assets/6375934/19739384/6400734a-9bc3-11e6-896a-65aa35732c72.png)
Furthermore, when launched as root (e.g. sudo gedit, sudo nautilus) a nice Gnome-style window appears (with no such border problem, because now there's no titlebar - so, as an Ubuntu user, I wonder where the menu went ;-)
I think there's a conflict between Gnome-style (header bar) window decoration and Unity-style window decoration here (see the screenshot below), and if this conflict cannot be resolved otherwise, probably a workaround like giving up that lighter shading/border at the top and even round top corners could be the only option left...
![screenshot from 2016-10-26 21-25-59](https://cloud.githubusercontent.com/assets/6375934/19739529/fa57a4f8-9bc3-11e6-881c-cc78565ba0b3.png)

**Comment by ochosi** [comment]
Unfortunately that is a side-effect of Ubuntu patching out the headerbars for some apps. I have already worked out a way to fix the theming for that but it means adding patches to all of these applications.

For now I really don't wanna change the headerbar style just because the toolbars in those apps suck, but I appreciate it's an issue.

**Comment by Sadi58** [comment]
I understand, but it's sad to see this great theme becoming less and less compatible with Unity. I'll try and see if I can make use of those app-specific css files in Ambiance theme, and report back to you.

**Comment by jbicha** [comment]
@ochosi , maybe this helps?
https://github.com/numixproject/numix-gtk-theme/commit/a457b8fd5

**Comment by ochosi** [comment]
@jbicha Awesome - thanks!

**Comment by jbicha** [comment]
@ochosi I'm going to SRU this for Ubuntu 16.10.

**Comment by Sadi58** [comment]
@jbicha @ochosi Thanks a lot! :-)

**Comment by ochosi** [comment]
@jbicha thanks that's great!
