### ISSUE TITLE
gtk 3.22.1: tabs too high

### ISSUE THREAD

**Issue by tambeta** [shimmerproject/Greybird#158]
I'm using the latest Greybird from git master on Arch Linux, GTK 3.22.1. The notebook widget tabs seem to be excessively high in (at least some) apps built against GTK3. For example, `xfce4-terminal` 0.8.x is built against GTK3, but the 0.6.x branch was built against GTK2 (to the best of my knowledge). Comparative screenshots attached. The same issue is present in `gnome-terminal`, so it's not isolated to a single application.

![xfce4-terminal-gtk2](https://cloud.githubusercontent.com/assets/9417744/19862478/2df47560-9f99-11e6-9c84-9006a7417a45.png)
![xfce4-terminal-gtk3](https://cloud.githubusercontent.com/assets/9417744/19862479/2df64728-9f99-11e6-8a90-6095a7431a98.png)

Proposed resolution: significantly decrease the height of GTK3 notebook tabs, to match GTK2.

Thank you again for the best GTK theme out there!

**Comment by f2404** [comment]
Please refer to the link posted here: https://bugzilla.xfce.org/show_bug.cgi?id=12796#c8

**Comment by tambeta** [comment]
Thanks, that works well as a stop-gap measure. I'm hoping the inconsistency between GTK2 and GTK3 will be fixed in Greybird itself, though.

**Comment by ochosi** [comment]
I've just pushed a change that makes tabs in normal applications the size of tabs in Gtk2, however this doesn't work for the terminal so far. I still have to figure out what's going on there exactly (not sure any of you remember, but even the Gtk2 terminal had this very same problem at some point).
