### ISSUE TITLE
Firefox suffers from graphical bugs after trying greybird theme

### ISSUE THREAD

**Issue by pprw** [shimmerproject/Greybird#160]
Hi everyone,

I am using Xfce and tried greybird, bluebird and darkbird themes. They change the way firefox appears with some little bugs (spacing between icon of the personal toolbar, menu, ...). I set back the xfce default theme but, even after a reboot, I still have some bug in firefox (only in firefox). The worse : the graphical bugs affects now another computer just because the two firefox profiles where synchronized (firefox sync).

So It seems firefox didn't like the try of some gtk3 theme and maybe somehow "tried to adapt". And now, when I just want to have back the basic Xfce default theme, I still have the bugs.

Is there a way to modify firefox to fix this?

**Comment by ochosi** [comment]
It's hard to believe that this would have anything to do with Greybird. If anything, it's a bug in Firefox (which doesn't use the Gtk+ toolkit directly but instead tries to mimick it).

You can try to remove the .cache and the .mozilla directories in your home to see whether that resets the erratic behavior.

**Comment by pprw** [comment]
Yes It's a bug related to the new version (49) of firefox. Using the firefox-esr release fixes it. Sorry for the noise.
