### ISSUE TITLE
Applications using header bars show a white line

### ISSUE THREAD

**Issue by raginggoblin** [shimmerproject/Greybird#162]
Using Ubuntu 16.10 (gtk3.20), applications using header bars show a white line under the header bar. See the difference between nautilus and thunar.
![nautilus](https://cloud.githubusercontent.com/assets/1873470/20276001/ce219aca-aa9a-11e6-862b-106c4419d12c.png)
![thunar](https://cloud.githubusercontent.com/assets/1873470/20276000/ce204580-aa9a-11e6-83a7-4cc6f4c89751.png)

**Comment by ochosi** [comment]
First of all, this is not a normal headerbar, but a patched-out headerbar (which is Ubuntu specific).

I've recently fixed this problem for most apps, but obviously Files was not one of them. Not sure I'll have time and motivation to go after this one too, tbh.
See this commit for reference: https://github.com/shimmerproject/Greybird/commit/0e57ca3f1bd7b604e9e27cb27e26ddd81d0e3f87

**Comment by ochosi** [comment]
Interesting, I can't reproduce this on 16.10. After installing Files (aka nautilus) it has a headerbar, so unlike what is seen in your screenshot.
What distro is this exactly (as it is obviously not Xubuntu)?

![screenshot_2016-11-15_23-37-23](https://cloud.githubusercontent.com/assets/261436/20327215/81cf026e-ab8c-11e6-9581-a089a5f32f68.png)

**Comment by raginggoblin** [comment]
I am on Ubuntu 16.10 with Unity. To test this properly I downloaded and installed a fresh version in Virtual box. This one showed up perfectly. I don't know whats wrong with my own system. But the theme is ok, it is somehow my own system that does not work properly. Closing this issue. Thanks again for this fabulous theme.

**Comment by ochosi** [comment]
Awesome, thanks for checking again and reporting back!

**Comment by jbicha** [comment]
I believe this is a duplicate of issue #157 . That was fixed in an update for Ubuntu 16.10 which is why you shouldn't be able to reproduce this bug any more once all updates have been installed. :)

Make sure you have greybird-gtk-theme 3.20.1-1ubuntu0.1 installed. It was just released as an update this week so it may not be installed on your system yet.
