### ISSUE TITLE
deja-dup: Progresslist too small

### ISSUE THREAD

**Issue by HeikoAdams** [shimmerproject/Greybird#164]
The progresslist of deja-dup seems to be missthemed
![bildschirmfoto_2016-11-20_10-35-41](https://cloud.githubusercontent.com/assets/1418818/20461908/33981d72-af0d-11e6-84c2-c0bc0d6883eb.png)

**Comment by jbicha** [comment]
I believe this is a deja-dup bug triggered by GTK 3.20+. See Launchpad [bug 1639464](https://llaunchpad.net/bugs/1639464) .

**Comment by ochosi** [comment]
Indeed, this definitely has nothing to do with Greybird. You can try with Adwaita to be sure.

FWIW I noticed this with some of the apps that I (co-)maintain with 3.20 and had to set expand or min-height values as well, so this definitely feels familiar...

@jbicha I think I don't tell you enough how awesome you are - thanks for your support!

**Comment by ochosi** [comment]
Anyway, seems not to be an issue with Greybird, hence closing.
