### ISSUE TITLE
BIG buttons on Synfig

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#166]
Some time ago I report a bug in Zukitre GTK Theme related with Synfig.
https://github.com/lassekongo83/zuki-themes/issues/81

This bug appears to in Greybird.

But today, I solved adding these rules:

window > box > widget > paned > paned > paned > notebook > header > widget > button,
window > box > widget > paned > paned > notebook > header > widget > button 
{
  min-height: 2px;
  min-width: 2px;
  height: 2px;
  width: 2px;
}

So, I notify this here. Maybe it could be useful. ;)

**Comment by ochosi** [comment]
Seems to be fixed in Synfig master branch: http://www.synfig.org/forums/viewtopic.php?t=10085#p32955
