### ISSUE TITLE
LibreOffice toolbar borders

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#167]
I know some apps like LO are rather tricky, but I wonder if these unseemly borders around toolbars (especially the uppermost one) could be tweaked a bit to achieve a more consistent and flat appearance...
Once again thanks a lot for this outstanding theme.
![screenshot from 2016-12-16 01-37-12](https://cloud.githubusercontent.com/assets/6375934/21244991/d65ecedc-c328-11e6-84d6-ce42b3640bf7.png)

**Comment by ochosi** [comment]
Hmm right, this is LO with Gtk3, which I personally haven't tried. I can try to fire it up one of these days, shouldn't be too hard to figure this out.
What distro/release are you on?

**Comment by Sadi58** [comment]
Sorry, I forgot, mine is Ubuntu 16.10.
I think the ideal could be a flat toolbar like others, but at least a darker shade (as in the apps like Chrome, Thunderbird, etc.) would look a little better than the current bright edges.

**Comment by jbicha** [comment]
@ochosi I think you'll find that theming LO is [painful](https://github.com/horst3180/arc-theme/issues/659) at least with 5.2.

Yes, Ubuntu 16.10 defaults to the GTK3 version of LibreOffice.

**Comment by cinquecento** [comment]
![libreoffice 5 3](https://cloud.githubusercontent.com/assets/10598241/21456171/0de57182-c8f4-11e6-9f1d-bed2166a0b9f.png)
There is support for gtk3, so it can be finely adjusted.
This is an example with a dark theme.

**Comment by Sadi58** [comment]
I've just heard that LO 5.3 is on the way with this problem sorted out ...hopefully.

**Comment by ochosi** [comment]
Yeah, tbh this issue sounds like it should be tackled in LO anyway. Themes shouldn't have to jump through hoops just to make toolbars look like their default selves.
