### ISSUE TITLE
The new Nautilus (3.20) notification

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#168]
After upgrading to Ubuntu 16.10  I now see a notification pop up (with an Undo button) at the top of the current pane following some actions like moving files to trash.
As seen in the screenshot below, I think it could look better (and more legible) with one or two tweaks - e.g. a darker bgcolor such as border immediately above, and/or much less transparency - as it's rather difficult to read it especially when there are folders and files in the background.
![greybird-nautilus-notification](https://cloud.githubusercontent.com/assets/6375934/21259194/097a5bb4-c389-11e6-8269-3eca8ef8317e.png)

**Comment by ochosi** [comment]
This should be improved/fixed with the latest 3.22.1 release. Could you please check? Thanks!

**Comment by Sadi58** [comment]
Yes, thanks a lot!

**Comment by Sadi58** [comment]
PS: A similar fine-tuning also for the "Undo" button text would make it perfect I think ;-)

**Comment by ochosi** [comment]
Hmm, could you post a screenshot of that?

**Comment by Sadi58** [comment]
It's a minor thing... If you feel like it...
![screenshot from 2017-02-13 21-13-49](https://cloud.githubusercontent.com/assets/6375934/22896544/425adae8-f229-11e6-9c1b-681809a56376.png)

**Comment by ochosi** [comment]
Oh wow, that looks bad... I'll see what I can do.

**Comment by ochosi** [comment]
Mind testing this branch? https://github.com/shimmerproject/Greybird/tree/gtk3_dark

(I had disabled the dark theme variant so far because in Xfce it mostly causes inconsistency for all apps that don't have a headerbar and CSD)

**Comment by Sadi58** [comment]
I also don't prefer using the dark theme variants because they always result in some invisible icons/texts here and there...
I've tested this, but couldn't see any difference... Maybe I should do something else to use the dark variant which I don't know (maybe because my DE is Unity, and not Gnome Shell)

**Comment by Sadi58** [comment]
OK, I changed the name of `gtk-dark.css` to `gtk. css`, and I think I've got what you wanted ;-)
**It looks beautiful**, except a couple of issues, including **lack of a similar dark variant for gtk2 apps** (e.g. Thunderbird)
As for gtk3 apps, at a glance I could only see a minor problem with **Nautilus sidebar**: its backdrop/unfocused colors should be the normal behavior it seems (including also the bgcolor of location/toolbar) as can be seen in the screenshots below.
**Active Window:**
![screenshot from 2017-02-15 17-39-08](https://cloud.githubusercontent.com/assets/6375934/22979241/5341d3cc-f39e-11e6-80c5-2937b3ef9c12.png)
**Backdrop/Unfocused Window:**
![screenshot from 2017-02-15 17-39-21](https://cloud.githubusercontent.com/assets/6375934/22979298/8ec2e760-f39e-11e6-9d5f-e9cba2c7e518.png)

**Comment by jbicha** [comment]
@Sadi58 The easiest way to use a dark variant is to install `gnome-tweak-tool` and turn the first slider on in the `Appearance` panel.

**Comment by Sadi58** [comment]
@jbicha Thanks. I uninstalled it sometime ago because it has become less and less useful for Unity, even causing some problems as far as I can remember.

**Comment by jbicha** [comment]
Feel free to install it only to change the settings and uninstall it after. I think it's easier than me telling you what to change in `~/.config/gtk-3.0/settings.ini`

**Comment by Sadi58** [comment]
@jbicha OK. I've done it ;-)
`gtk-application-prefer-dark-theme=1`
As far as I can see in Unity Tweak Tool, Shotwell, Gnome Image Viewer, Document Viewer, Calculator, Terminal, gedit; it's working perfectly!
But problems pop up when you open non-Gnome gtk3 apps: e.g. my favorite text editor KKEdit requires dark icon theme (for its toolbar), which results in almost invisible icons in the toolbar of others like Synaptic Package Manager as well as gtk2 apps.

**Comment by Sadi58** [comment]
As I've said, either this way or directly selecting any dark theme (those with only dark titlebar/toolbar/menubar, or full dark ones), dark themes always cause a mess, or a lot of inconsistencies at the least -- Ambiance, Numix, Vertex, I've tried all; and finally decided to forget about it all ;-)
The best for Ubuntu at least is a silver theme like Greybird ( with no "darkness" involved ; -)

**Comment by Sadi58** [comment]
BTW, I normally use a slightly tweaked version of Greybird (named "Graybird") by **simply symlinking** subfolders and files to my local Greybird git repository, except a couple of files like `./gtk-3.0/gtk-contained.css`.
However, I don't have `./gtk-3.0/gtk.gresource` in such a manual setup.
Although it appears to be working just fine, **I wonder if I'm missing anything**...

**Comment by ochosi** [comment]
@Sadi58 Has this issue been resolved meanwhile? I'm still not using Nautilus so I don't test/see those notifications.

**Comment by Sadi58** [comment]
@ochosi Nautilus sidebar has a nice dark (black) bgcolor now.
The only outstanding (minor) issue is the Undo button text in the infobar (which could look better with shadow and text colors swapped perhaps) although I'm very happy with the way things are ;-)
Greybird is the closest thing to perfection in GTK theming, and thanks a million for this!

**Comment by ochosi** [comment]
Allllllright. So I installed Nautilus...

**Comment by Sadi58** [comment]
@ochosi Thanks a lot, it's perfect now! And after the latest decision to abandon unity for future versions of Ubuntu, I think I'll make this change immediately: so fed up with such problems of inconsistency with the base Gnome DE...
