### ISSUE TITLE
Can the button(s) size be reduced in certain applications?

### ISSUE THREAD

**Issue by kepler2** [shimmerproject/Greybird#169]
Hello. First of all I would like to thank you for the great work you are doing with the Greybird theme. Been a fan since long time ago. 

Currently I'm using Arch XFCE (with GTK > 3.20). I have come across an issue. It seem that, for example, in the Notifications app, the top buttons (Appearance / Applications) and the ON / OFF buttons appear too large. I have attached, for comparison, some screenshots when using the Arc theme vs Zukitwo vs Greybird.

Could the button sizes be reduced for consistency?

Thanks

Arc:

![arc](https://cloud.githubusercontent.com/assets/18610924/21293326/8caf2c52-c529-11e6-90cf-9f257977ae01.png)

Zukitwo:

![zukitwo](https://cloud.githubusercontent.com/assets/18610924/21293339/e882566c-c529-11e6-8362-0821d86ab7e2.png)

Greybird:

![greybird](https://cloud.githubusercontent.com/assets/18610924/21293327/927ed088-c529-11e6-855e-333b742624d6.png)

**Comment by ochosi** [comment]
Yup, I agree, the old style (inherited from Adwaita) looked puffy. Should be better now.
