### ISSUE TITLE
Odd window control buttons in some apps started with sudo or gksu

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#170]
I see this with nautilus and gedit (I think some other Gnome default apps, too) but not all apps like gparted or synaptic under Ubuntu 16.10 (64-bit), and I don't have this issue in some other themes, e.g. [MacOS-Sierra](https://github.com/B00merang-Project/macOS-Sierra)
![greybird gedit sudo 2017-02-02 16-01-29](https://cloud.githubusercontent.com/assets/6375934/22550777/68c3b4f2-e95a-11e6-9360-13bb4497e92a.png)

**Comment by ochosi** [comment]
Do you have Greybird installed in a systemwide location or in your home folder?

**Comment by Sadi58** [comment]
I've installed it in my home folder, but it's symlinked to the root folder as well, so it should be OK.
I've tested this setup many times, and it passed all the tests. Besides the other theme (MacOS-Sierra) is in the same location, and this issue doesn't affect many other apps run as root, which is really odd, at least for me.
I kind of liked those buttons by the way; I would just swap them for the sake of consistency if I could find where they come from (probably hardcoded somewhere in Gnome.

**Comment by jbicha** [comment]
I don't think that's a theme-specific bug.

What you are seeing in the second screenshot is the GNOME headerbar. The headerbar is patched out for core Ubuntu apps when running Unity. Unity doesn't currently support using sudo for apps like gedit or nautilus, at least not with theming. You could try reporting this issue on Launchpad against one of those apps.

If you really like the headerbar, you could run Ubuntu GNOME, but of course that has a lot of other differences too…

I wish it were easier to opt in or opt out of the headerbar in Ubuntu but I'm not sure how to implement that.

**Comment by Sadi58** [comment]
@jbicha Initially I also thought it was a result of some clumsy patching in the process of porting those Gnome core apps to Unity.

But what changed my mind and report this as an issue here was the theme **MacOS-Sierra** mentioned above, which is also under `~/.themes` which is merely symlinked to `/root/.themes`. And it seems to me the secret might perhaps be in their file named `gtk-widgets-assets.css`, containing references to buttons, which I think you might be able to spot in a matter of seconds while as an ordinary user it might take hours -if not days- for me to find what really makes the difference by trial and error ;-)

**Comment by ochosi** [comment]
Alright, I'd say this is no Greybird issue either way. Thanks for clarifying, @jbicha!

**Comment by Sadi58** [comment]
Hmm, you're the boss ;-)
But it seems to me that you don't want to try to solve this issue ;-)
I would say MacOS-Sierra is not as complete and highly developed as Greybird, but it doesn't have this problem. So this should be an indication that there's something that can be done to eliminate this inconsistency...

**Comment by ochosi** [comment]
@jbicha In theory you could make the headerbar on/off a global setting like the overlay scrollbars had it in Ubuntu and how the new gtk3 scrollbars have it. Would mean more patching applications and you couldn't be sure it'd work everywhere...

@Sadi58 I don't mind reopening the bug, but I'll be honest: it's very unlikely to install Unity to reproduce this... If you wanna try to find out how to fix it I'll gladly take a patch (if it really turns out to be a theme issue after all)

**Comment by Sadi58** [comment]
OK, I'll try to find something useful.

**Comment by Sadi58** [comment]
It seems adding a section from **MacOs-Sierra** theme does the job, with a little hover effect issue.
I've managed to replace those Gnome default buttons, but not that grey rectangular outline that appears as hover effect - without that lighter background though.
My hover/prelight buttons appear properly but that **Gnome default grey rectangular outline** also shows up in addition! And this is merely repeated **when a button is pressed** as well (no change to active/pressed button)...
**I wonder if anyone can suggest a possible change in the code below...**
![screenshot from 2017-02-08 13-46-59](https://cloud.githubusercontent.com/assets/6375934/22734098/2ff6e7fa-edfd-11e6-8ca4-cf2050942c0e.png)
```
/***************************
 * Unity headerbar buttons *
 ***************************/

.titlebar .titlebutton.close {
    color: transparent;
    border-image: none;
    box-shadow: none;
    background-position: center;
    background-repeat: no-repeat;
    background-image: -gtk-scaled(url("./assets/titlebutton-close.png"));
}

.titlebar .titlebutton.close:active,
.titlebar .titlebutton.close:checked  {
    color: transparent;
    border-image: none;
    box-shadow: none;
    background-position: center;
    background-repeat: no-repeat;
    background-image: -gtk-scaled(url("./assets/titlebutton-close-active.png"));
}

.titlebar .titlebutton.close:hover {
    color: transparent;
    border-image: none;
    box-shadow: none;
    background-position: center;
    background-repeat: no-repeat;
    background-image: -gtk-scaled(url("./assets/titlebutton-close-hover.png"));
}

.titlebar .titlebutton.close:backdrop {
    color: transparent;
    background-image: -gtk-scaled(url("./assets/titlebutton-close-unfocused.png"));
}

.titlebar .titlebutton.maximize {
    color: transparent;
    border-image: none;
    box-shadow: none;
    background-position: center;
    background-repeat: no-repeat;
    background-image: -gtk-scaled(url("./assets/titlebutton-maximize.png"));
}

.titlebar .titlebutton.maximize:active,
.titlebar .titlebutton.maximize:checked  {
    color: transparent;
    border-image: none;
    box-shadow: none;
    background-position: center;
    background-repeat: no-repeat;
    background-image: -gtk-scaled(url("./assets/titlebutton-maximize-active.png"));
}
```

**Comment by ochosi** [comment]
@Sadi58 I have a half-working version of loading png assets for window controls in Greybird now (it actually works fine, but I'm lacking support for dark and hidpi versions). I'll try to push it asap.

**Comment by ochosi** [comment]
Works now for normal and dark variant.
The hidpi version also works but is still a bit fuzzy (would be nice to upscale all the current 16x16 to sharp 32x32 icons).

**Comment by Sadi58** [comment]
Thanks!
But this was ages ago, and since then I've switched to Linux Mint, where there's no such issue anyway ;-)
You see, I was tired of such frequent changes in GTK3 resulting in broken themes, etc. and I think I've found a good balance of a stable base plus a modern look and the latest apps in Linux Mint.
