### ISSUE TITLE
Add more padding for buttons?

### ISSUE THREAD

**Issue by jbicha** [shimmerproject/Greybird#171]
Maybe Greybird intentionally uses less padding than Adwaita?
In this case the < > buttons and the buttons in the top right look too cramped to me.

Adwaita
----------
![gnome-calendar-adwaita](https://cloud.githubusercontent.com/assets/876259/22951289/a361de38-f2d6-11e6-8dec-dab24a9cb3de.png)

Greybird
-----------
![gnome-calendar-greybird](https://cloud.githubusercontent.com/assets/876259/22951290/a367481e-f2d6-11e6-81b3-5599ac11ddb2.png)

System Info
---------------
Ubuntu GNOME 17.04 Alpha
Running gnome-shell
gnome-calendar 3.23.90-0ubuntu1
greybird-gtk-theme 3.22.1-1
gtk+ 3.22.7-1ubuntu2
gnome-themes-standard 3.22.2-1ubuntu1

**Comment by ochosi** [comment]
Agreed, I should add more horizontal padding to those image-buttons.

**Comment by ochosi** [comment]
Feel free to reopen if there are more issues with it.

**Comment by jbicha** [comment]
Thanks, this looks better in gnome-calendar now!

And the dark theme is interesting. I had been using Adwaita Dark but Greybird Dark is currently pretty similar to it.

**Comment by ochosi** [comment]
Yeah, as Greybird is based on Adwaita I also inherited the dark theme. And as I haven't fiddled with it much (apart from trying to make sure it works okayish) it should feel fairly similar.
