### ISSUE TITLE
HiDPi support

### ISSUE THREAD

**Issue by g3blv** [shimmerproject/Greybird#172]
I'm running Xubuntu 16.04 on a Dell XPS 13 with a QHD display. I'm using the Greybird theme but at the moment everything is tiny on the screen and I'm trying to find the right settings for QHD/HiDPi. Reading [this](https://forums.bunsenlabs.org/viewtopic.php?pid=33837#p33837) it seems like Greybird is a HiDPi theme while reading [this](https://github.com/shimmerproject/Greybird/issues/100) it seems like Greybird doesn't support HiDPi. Is there support for HiDPi in Greybird? And if there is support for HiDPi how do I set it up correctly?

**Comment by ochosi** [comment]
In short: yes, Greybird (the Gtk3 theme) does support HiDPI.

However, not everything (or in fact: little) of your desktop environment uses the Gtk3 toolkit, most of it is still Gtk2. And Gtk2 does **not** support HiDPI. This is a feature that comes with Gtk3.

So I can only advise you to try e.g. the settings manager in its Gtk3 variant (then it also has a switch to go from the 1x scaling to the 2x scaling, which you'll definitely need) and basically whatever you can get in Gtk3. For Gtk2 apps you're left with playing with the DPI settings in the appearance settings dialog. There are various PPAs by the xubuntu-devs group on Launchpad that you can use for testing, e.g. this one here: https://launchpad.net/~xubuntu-dev/+archive/ubuntu/xfce4-gtk3

Also, the Xfwm4 theme of Greybird (read: the window borders theme) does not yet have a 2x variant that would be appropriately sized for your resolution. I just haven't had one of those displays here for me so I haven't worked on this.

**Comment by ochosi** [comment]
Anyway, not really an issue with Greybird, but more related to Xfce and Gtk2/3.
