### ISSUE TITLE
Two horizon horizontal lines appear on the login panel.

### ISSUE THREAD

**Issue by d0u9** [shimmerproject/Greybird#173]
![1887418920](https://cloud.githubusercontent.com/assets/7038479/23824975/2062ee56-06bc-11e7-9866-a71cb85f34ad.jpg)

lightdm: 1.20.0
OS:arch linux
greybird version: from aur 3.22.2-1

**Comment by d0u9** [comment]
solved by updating arch linux to the latest.

**Comment by ochosi** [comment]
Updating to the latest Gtk+ release or the latest Greybird?
