### ISSUE TITLE
Buttons are not completly visible in GNOME File Roller

### ISSUE THREAD

**Issue by Feichtmeier** [shimmerproject/Greybird#186]
The buttons in this dialoge frame are not fully visible. GNOME File Roller 3.22.3

I am not sure if this is wanted or not but I think it looks unwanted. Not a big issue :)
![bildschirmfoto von 2017-05-08 10-41-52](https://cloud.githubusercontent.com/assets/15329494/25796796/40c66fa0-33db-11e7-93cb-6fbffdc01447.png)

**Comment by ochosi** [comment]
Yeah, that's definitely a bug. Will have to check with file-roller myself to see what kind of dialogue this is so I can remove the margin of the buttons in this context

**Comment by ochosi** [comment]
Hmm, I have 3.22.1 on Ubuntu and this is how it looks
![screenshot_2017-05-09_23-36-38](https://cloud.githubusercontent.com/assets/261436/25873881/6d7cc680-3510-11e7-86e4-a7a4adc3d04e.png)

**Comment by jbicha** [comment]
@Feichtmeier Please also specify what distro you are using, what version of Greybird you are using and where you got it from (distro package or not).

**Comment by Feichtmeier** [comment]
Ubuntu GNOME 17.04
Greybird version is... I cloned it yesterday from this repository (sorry I don't know where to check)
I have to specify that this bug also affects nautilus not only the file-roller (see the screenshot)
![bildschirmfoto vom 2017-05-10 11-27-09](https://cloud.githubusercontent.com/assets/15329494/25892105/a39b598a-3573-11e7-9978-af13769c395b.png)

**Comment by ochosi** [comment]
Would you mind opening the gtk inspector on those buttons and showing me the "CSS Nodes" part on a screenshot? Maybe that'd help with coming up with a patch...

**Comment by Feichtmeier** [comment]
![screenshot from 2017-07-05 13-34-55](https://user-images.githubusercontent.com/15329494/27862684-c69efd3a-6186-11e7-8e7a-61efff722904.png)

Sorry for the late answer.

**Comment by ochosi** [comment]
Thanks for the screenshot, I have pushed a branch with a possible fix, please test! Thanks!

**Comment by Feichtmeier** [comment]
Looks good! I think that is fixed:

![screenshot from 2017-07-10 20-21-24](https://user-images.githubusercontent.com/15329494/28033182-90cede02-65ad-11e7-8b32-94c34bfd4f60.png)

**Comment by ochosi** [comment]
Great! Thanks for checking back and testing this.
