### ISSUE TITLE
Switch Greybird from autotools to meson

### ISSUE THREAD

**Issue by jbicha** [shimmerproject/Greybird#187]
I think it might be useful if Greybird switched to [meson](http://mesonbuild.com/) instead of autotools.

Several high-profile projects have [switched](http://mesonbuild.com/Users.html) to it and several GNOME modules will switch later this year.

I might work on this eventually if you don't mind.

**Comment by ochosi** [comment]
I probably won't mind the switch, although I haven't looked at meson at all. It wouldn't be high priority for me because the build time with autotools is also fine for Greybird (not sure what other benefits to expect).

Anyway, I'll be interested to see that :)

**Comment by m4u9** [comment]
We switched to meson some time ago and missed this issue. Closing it as resolved :)
