### ISSUE TITLE
Making xfwm windows corners appearance more alike to GTK3 corners (patch included)

### ISSUE THREAD

**Issue by UgoYak** [shimmerproject/Greybird#188]
Hi there, I really like Greybird (and Greenbird by heritage) theme, but annoy me a little the difference between XFCE apps windows corners and GTK apps windows corners, as is shown in next image   (I'm using Xubuntu 16.04.1):

![Corners](http://i.imgur.com/xJBNHbe.png)

So, based on "Greybird Accessibility" I edited the XFWM corners assets, and now looks very close to the GTK3 style, and more alike between applications:

![Corners Fixed](https://cloud.githubusercontent.com/assets/13735486/26082089/515672e2-39a4-11e7-8238-381dc98980d1.png)

This are the eight files what I modified:

![Files](http://i.imgur.com/0b1LL4u.png)

And here is the [link to the package with them](http://www.mediafire.com/file/eersqvyswmujp5x/borders-fix-greybird-greenbird-for-xfwm-2017.zip)

I replace the existent files on: **/usr/share/themes/Greybird/xfwm**

Thanks again for maintain this great theme! ;)

(Sorry for the bad english)

**Comment by ochosi** [comment]
Hi there!
Thanks for noticing the inconsistency and the hard work!
I know this sucks for you since you already patched the Xfwm4 part, but I'd prefer to fix the client-side decorations (what you call the Gtk3 decorations). I'll look into that part myself and if I fail I will reconsider going your way.

**Comment by ochosi** [comment]
I just tested this again with Greybird from git master and the only difference I can notice between the xfwm4 theme and client-side decorations is that the latter are anti-aliased. The radius is the same (see exhibit 1 and 2).
![exhibit1](https://cloud.githubusercontent.com/assets/261436/26563268/d6053bf0-44cf-11e7-93f5-570923aa7f03.png)
![exhibit2](https://cloud.githubusercontent.com/assets/261436/26563269/d60b4be4-44cf-11e7-94f4-939800001fc3.png)

**Comment by UgoYak** [comment]
So, I guess Xubuntu 16.04.1 is using a really older version... Well, I will try updating the theme with the git version (I already tried some time ago but I had some problems with apps with client-side decoration ). Well, thanks for take a look!
