### ISSUE TITLE
Thin bar visible in gedit/xed

### ISSUE THREAD

**Issue by haarp** [shimmerproject/Greybird#189]
Using the newest version of the theme. There's a tiny bar, maybe 1 or 2 pixels wide, visible in the text area of gedit or xed. It lights up when you try to scroll up but you're already at the top of the document. See screenshot:

![screenshot_2017-05-17_21-03-26](https://cloud.githubusercontent.com/assets/781030/26171209/6742fade-3b44-11e7-98df-9faa88fe3790.png)

**Comment by ochosi** [comment]
Hi, could you give me more information about your system? (Gtk+3 version, Distro, Distro release etc)
Thanks!

**Comment by haarp** [comment]
gedit-3.10/xed-1.4.1, GTK+ 3.22.15, Gentoo Linux (rolling release)

**Comment by haarp** [comment]
It appears to be the exact same width as the search box that appears when ctrl+f is pressed.

**Comment by ochosi** [comment]
Gedit 3.10 together with Gtk3.22? Is that even supposed to work?

Anyway, that'll be hard for me to test, I'm on Gedit 3.22 with Gtk 3.22.

**Comment by haarp** [comment]
Alas, gedit-3.10 is the last usable version of gedit :(

Try linuxmint/xed, it shows the same bar

**Comment by ochosi** [comment]
Could you check whether this commit helps with your issue? https://github.com/shimmerproject/Greybird/commit/b5875735ca5e720a30e7b21724d6be9d43499af8

**Comment by haarp** [comment]
No more weird bar. Thanks! :)
