### ISSUE TITLE
Icons in xfdesktop 4.13

### ISSUE THREAD

**Issue by giovannicaligaris** [shimmerproject/Greybird#193]
With xfdesktop 4.13 (I've been using the version from the gtk3-rebased branch), it's hard to tell which icons are selected and which ones aren't.

A member in the XFCE buzilla has found a solution

https://bugzilla.xfce.org/show_bug.cgi?id=13609

I think it should be implemented in the next version of Greybird.

**Comment by ochosi** [comment]
Hi Giovanni, I know about this problem but am looking for a solution for xfdesktop itself to not look broken out of the box.
Lately I was too busy with porting the xfce4-panel, but it's on my to-do list

**Comment by giovannicaligaris** [comment]
Awesome, thank you!
