### ISSUE TITLE
pavucontrol notebook tabs don't have the appropriate bg color

### ISSUE THREAD

**Issue by kepler2** [shimmerproject/Greybird#194]
Hello! First of all thanks for the work you are doing. Greybird is a very nice theme I use it although the Arc theme has become pretty standard it seems. I have some small issues i wanted to share, and of course, was wondering if they are subject to change (it would be nice).

OS: Arch 
Theme: Greybird (AUR)

The toggle (select) buttons seem very large (compared to Arc theme for example):

Greybird:

![greybird](https://user-images.githubusercontent.com/18610924/27631724-148415d8-5c02-11e7-9ed4-7130e4cb5b58.png)

Arc:

![arc darker](https://user-images.githubusercontent.com/18610924/27631579-95022322-5c01-11e7-970a-d365a0d01528.png)

Also, the top menus seem larger than usual and don't appear to blend in with the theme

Greybird:

![greybird_volume](https://user-images.githubusercontent.com/18610924/27631627-cc5645ba-5c01-11e7-90cc-2ab3b915134b.png)

Arc (looks is consistent with the theme)

![arc_volume](https://user-images.githubusercontent.com/18610924/27631660-df38605a-5c01-11e7-9001-ce16b6defefd.png)

Thanks a lot

**Comment by ochosi** [comment]
Hi,

so the first issue (size of switches) has already been tackled several times. Greybird is somewhere mid-way between Adwaita and Arch, so I'm not extremely concerned.

pavucontrol (which is the second example you're showing) is unfortunately a little broken in terms of UI for a while already, it seems to be only semi-maintained. I can look into fixing that one up again (I've done so already several times it the past).

**Comment by kepler2** [comment]
Thanks for the info and for your work. Are you the only man working on this theme? I mean Xubuntu has your theme as the default...

**Comment by ochosi** [comment]
@kepler2 Yes, I originally created the theme for Xubuntu, of which I've been the artwork lead for several years. There were some contributions from others over the years but it's mostly been me.

**Comment by kepler2** [comment]
Congrats. Most of the people take things for granted these days. I would contribute but my knowledge is limited regarding theming / code etc.

I'm not really a perfectionist but I like clean themes and consistency. **Greybird** theme is one of my favourites, but like I have shown you, it has some minor issues, which, of course, might be fixed or not. 

Is there any way I can modify some aspects of the theme? (beginner material :)

Thanks !

**Comment by ochosi** [comment]
Thanks! :)

To be frank the pavucontrol issue is more in pavucontrol than in Greybird.

Modifying the theme is not hard, just check the scss files, run make and make install. The hardest part is surely keeping consistency between Gtk2 and 3 because of the limitations of the former.

**Comment by ochosi** [comment]
This needs more poking. Setting the stack color explicitly breaks a lot of other things...

**Comment by ochosi** [comment]
This can finally be closed due to 8e74c381b0fdc281a36e2cdcae0b3d1c693070bc
