### ISSUE TITLE
Little changes to make CAJA uniform

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#195]
Hi!

I've noticed Caja does not look very integrated with Greybird than Thunar is.

Here, Thunar with Greybird (looks like so great):

![screenshot25](https://user-images.githubusercontent.com/5833446/27681676-520ed83e-5cc0-11e7-916b-b5cd41bda09a.png)

And here, Caja with Greybird (looks like a bit ugly when left panel is active because the panel borders):

![screenshot24](https://user-images.githubusercontent.com/5833446/27681727-73840cdc-5cc0-11e7-9497-1f845c67cab4.png)

And here, two suggestion about how could be Caja:

In this one, you can see a little change in borders between the main and the left panels. Looks like much better:

![screenshot24b](https://user-images.githubusercontent.com/5833446/27681862-d5da68cc-5cc0-11e7-883e-8d6be5a026b8.png)

And in this one, you can see a version similar to Thunar, with dark background in left panel:

![screenshot24c](https://user-images.githubusercontent.com/5833446/27681936-1c6d0ec0-5cc1-11e7-999d-1a3831f18d2a.png)

It would be possible to change the Caja styles to do that?

Thanks a lot for this awesome theme! ;)

**Comment by ochosi** [comment]
The easiest way would be for caja to use the sidebar class, then the theming would simply be right in all themes...

**Comment by jEsuSdA** [comment]
Reported to the Caja mantainers.
I hope they could add the class. ;)

**Comment by jbicha** [comment]
@jEsuSdA You could also try upstream at https://github.com/mate-desktop/caja/issues

**Comment by jEsuSdA** [comment]
Done! 
https://github.com/mate-desktop/caja/issues/805

**Comment by raveit65** [comment]
I am MATE theme artist.
Caja needs a theming for the sidebar, as we provide different views for it. See our BlueMenta theme as esample.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L126
This needs to be done by greybird theme.

**Comment by raveit65** [comment]
And we don't use the sidebar class as adding this requires a sidebar code rewrite.
And we have more sidebar views than nautilus or nemo.
Feel free to use BlueMenta/Menta theme as template.

**Comment by ochosi** [comment]
I refactored that css into some cleaner scss, please test: https://github.com/shimmerproject/Greybird/tree/caja_support

**Comment by jEsuSdA** [comment]
Hi!

I've tested it and this is the result:

![screenshot6](https://user-images.githubusercontent.com/5833446/28209237-f3389cea-6891-11e7-9fdd-80909399cd92.png)

The color changes, but the borders and integration looks like before:

![screenshot5](https://user-images.githubusercontent.com/5833446/28209254-0521828c-6892-11e7-9d5e-019e4ebfcf72.png)


Thank you for your efforts. ;)

**Comment by ochosi** [comment]
I only took care of the sidebar in my patch, so if that's working thats fine. The borders indeed look a bit off, not sure why that's the case, I can check again.

What is the second screenshot about - is that a variant of the sidebar that is still unthemed?

**Comment by jEsuSdA** [comment]
The second screenshot is Caja with normal Greybird, the first one, Caja with Greybird with caja patches.

The only thing that changes is the bacground color. I think the border are more important and it will fantastic to do something like that:

![imagen](https://user-images.githubusercontent.com/5833446/28237552-659c05d2-6942-11e7-97f7-efdcb1d65a62.png)

**Comment by jEsuSdA** [comment]
Casually, the changes made in the toolbar and frame styles in #203, solves the CAJA look and feel, and with these patches, it looks like great again:

![screenshot60](https://user-images.githubusercontent.com/5833446/29252908-70878ce2-8070-11e7-8141-f1aa90d7177d.png)

As the double borders in panels disappeared, and the toolbar have a button border that separates the top and the rest, the result is beautiful. ;)

**Comment by jEsuSdA** [comment]
Caja bug closed! ;)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867162

The caja side class is `.caja-side-pane`.

;)
