### ISSUE TITLE
Libreoffice Print Dialog - selected tab has the same color

### ISSUE THREAD

**Issue by Feichtmeier** [shimmerproject/Greybird#200]
When I select a tab in the nautilus options the color changes to light grey. In the libreoffice print dialog it does not. I have the libreoffice-gtk3 package installed (which is not installed by default in xubuntu I think)

![screenshot from 2017-07-14 11-34-45](https://user-images.githubusercontent.com/15329494/28207126-ca6a850c-6888-11e7-821b-c0a3dd688192.png)
![screenshot from 2017-07-14 11-35-13](https://user-images.githubusercontent.com/15329494/28207140-d55e78e2-6888-11e7-9e15-ca831b9c060c.png)

**Comment by ochosi** [comment]
Not sure libreoffice itself isn't at fault there, it has its own print dialog and uses Gtk in weird ways... Does it look ok with all other themes?

**Comment by Feichtmeier** [comment]
Oh... yes, sorry. It is the same with other themes even with adwaita. I guess you can close it then, sorry.

**Comment by ochosi** [comment]
Ok thanks for cross checking.
