### ISSUE TITLE
The dates are the same color as the week numbers in the calendar

### ISSUE THREAD

**Issue by AXDOOMER** [shimmerproject/Greybird#201]
Other themes make it evident that the week numbers on the calendar are different from the dates, which is not done in Greybird and can lead to some confusion. 

How it looks in Greybird:
![](https://user-images.githubusercontent.com/6194072/28742431-f4a682aa-73fd-11e7-9362-aff96ad81e8a.png)

How it looks in other themes:
![](https://user-images.githubusercontent.com/961604/28743210-8f6f52ee-7444-11e7-8864-6a5397339fa0.png)

I am using MATE as my desktop.

**Comment by ochosi** [comment]
Could you check how it looks with Adwaita, the Gtk+ default look?

**Comment by AXDOOMER** [comment]
With Adwaita:
![screenshot at 2017-07-30 14-27-24](https://user-images.githubusercontent.com/6194072/28755948-6a0d9548-7533-11e7-99b0-c8badd2b45c4.png)

**Comment by ochosi** [comment]
Are you sure you're using the latest version of Greybird?

This is how the calendar should look (and does look here)
![screenshot_2017-07-31_00-37-28](https://user-images.githubusercontent.com/261436/28757675-898f73be-7588-11e7-806b-8c4739b4aa07.png)

The changes were released with Greybird 3.22.3

**Comment by AXDOOMER** [comment]
I'm on Debian 9, so the latest version that's available of `greybird-gtk-theme` is `3.22.0-1` and that's what I have installed. I'll wait until this version is made available on my distro. Thanks for the info.
