### ISSUE TITLE
SUGGESTION: Recover the old and fashioned toolbar gradient

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#203]
Hi!

I detected that the GTK2 and GTK3 Greybird versions are a bit different. This is normal, of course, but I think there is a nice lost style: the toolbar background gradient.

If you look any GTK3 app, you can look something like that:

![screenshot61](https://user-images.githubusercontent.com/5833446/29252525-6790ac38-8069-11e7-97e6-2d80128f3c20.png)

The background window is totally plain. Only a little gradient is found in window frame.

But if you load a GTK2 Window, you can see that:

![screenshot66](https://user-images.githubusercontent.com/5833446/29252536-b9cc7374-8069-11e7-979f-2c5a4b94597f.png)

Look at the toolbar: there are a beautiful and Greybird's characteristic gradient background and a 1px button border. I like it.

So, I've tried to make something similar in GTK3 Greybird styles, adding this:

```
/* hacks for toolbars with old fashioned gradient */
toolbar
{
	background-image: -gtk-gradient (linear,
    left top,
    left bottom,
    color-stop(0.0, #cecece),
    color-stop(0.50, #cecece),
    color-stop(1.00,#B8B8B8));
	border-bottom:1px solid #939393;

}
/*This is added to ensure a good separation between tabs an toolbars*/
notebook
{
	margin-top:3px
}

/* Hack for removing frame borders to avoid 2px size in toolbar button border*/
.frame
{
	border:0;
}
```

And this is the result:

![screenshot60](https://user-images.githubusercontent.com/5833446/29252557-2bbe63de-806a-11e7-91af-da2bd86c572a.png)

With this, the GTk3 apps looks like the GTk2 apps and the Greybird theme gains consistency.

I know my code must be improved, but my knowledge of GTK Styling is very poor, so, could you consider to add this to the main theme?

Thank you! ;)

**Comment by jEsuSdA** [comment]
NOTE: The only app I noticed fails to renders totally fine (with this toolbar gradient and with any other GTK themes that stylized the toolbars) is Synaptic:

As you can see, the toolbar does not fill the entire window:
![screenshot63](https://user-images.githubusercontent.com/5833446/29252587-b186265a-806a-11e7-8b6b-933308558ca8.png)

So, the gradient breaks before.

I'm sure this is a bug of the Synaptic itself, but I've tried to solve it with this code:

`/* hacks for synaptic */
window > box > paned > box > widget > button
{
	margin-right:3px;
/*	border-top:1px solid red;*/
}



window > box > paned > paned > box
{

	border-top: 1px solid grey;
	border-right: 1px solid grey;

}


window > box > box
{
	background-image: -gtk-gradient (linear,
    left top,
    left bottom,
    color-stop(0.0, #cecece),
    color-stop(0.50, #cecece),
    color-stop(1.00,#B8B8B8));
	border-bottom:1px solid #939393;
}
`
Notice this two things:

- I know this code is extremely ugly but I don't know how to manage the correct GTK CSS selectors. It will be really fine to find a way to apply any rule only for Synaptic. **If you know how to do, please, tell me. I want to learn**.

- This CSS rules affects to other apps. A few and a bit only, but this makes some apps to have a 2px button border in Toolbars. So, there are apps with 1px and other with 2px border, and this is not a pretty thing. So, I discard the window > box > box CSS rule. In addition, it makes the toolbar to have two backgrounds and borders... this is not good.

![screenshot64](https://user-images.githubusercontent.com/5833446/29252680-d4762ae2-806b-11e7-949d-6665fd47eb12.png)


- The two first rules are for adding some borders and buttons padding to improve Synaptic look and feel.

**Is there any way to make several GTK3 CSS Rules ONLY FOR AN APP and don't affect the rest of applications?**

Thanks!

**Comment by jEsuSdA** [comment]
Improvements for Firefox and Thunderbird to have the gradient:

- https://github.com/shimmerproject/Greybird/issues/197#issuecomment-322205524
- https://github.com/shimmerproject/Greybird/issues/198#issuecomment-322204277

;)

**Comment by ochosi** [comment]
Indeed, we should re-add that gradient to Gtk3 toolbars. Since you seem to have it working already feel free to submit a pull-request.

Synaptic sucks a little in that respect (just like pavucontrol) - unfortunately it's always been like that...

**Comment by jEsuSdA** [comment]
@ochosi 

Hi! Sorry to be lost these days. I was on holidays. ;)

How can I submit a pull-request. I have no much knowledge about git and github.
I'll do if you teach me how to do. Please.

Thanks! ;)

**Comment by stefson** [comment]
For a pullrequest you'd have to fork the original project, then download your fork via git to have it locally. You edit your files, you commit the changes, but to see the commits online you have to push them to your fork. Now you can create a pullrequest with the original project as the master and your own fork to be merged to it. The pullrequest can be edited by commiting locally and push this to forked repo.

**Comment by jEsuSdA** [comment]
@stefson , thank you.
I'll try to do it. ;)
