### ISSUE TITLE
Doesn't apply for gtk2 apps when installed in $HOME/.local/share/themes

### ISSUE THREAD

**Issue by andreldm** [shimmerproject/Greybird#205]
When the user tries to install without admin privileges, as described in README, it will not work for gtk2 apps. When the files are moved to $HOME/.themes (`mv $HOME/.local/share/themes/Greybird* $HOME/.themes`) it works.

**Comment by udp** [comment]
Can reproduce. FreeBSD 11.2

**Comment by ochosi** [comment]
@jbicha Any clue?

**Comment by jbicha** [comment]
My guess is that maybe gtk2 never supported $XDG_DATA_HOME.

https://developer.gnome.org/gtk3/stable/ch32s03.html

I don't use any gtk2 apps though.

**Comment by ochosi** [comment]
@andreldm Is this still an issue or can I go ahead and close this?

**Comment by andreldm** [comment]
@ochosi the only gtk2 app I have installed is gimp which does its own theming, using this [sample](https://gist.github.com/andreldm/0f2e45882a33b67b59b13547f2d60c5f) I can still reproduce the issue.

Your call, I would close as WONTFIX because gtk2 is not that relevant anymore and installing in ~/.local is also not that common, an edge case IMHO.

**Comment by ochosi** [comment]
Cool, closing then.
