### ISSUE TITLE
Make Gnome Shell desktop icon text colours brighter (white)

### ISSUE THREAD

**Issue by ghost** [shimmerproject/Greybird#208]
Hello, I'm using the Greybird theme on both Gnome and Lxde; and the desktop icons text is really difficult to see. These are comparison snapshots between Greybird and Adawita themes:

Greybird:
![1](https://user-images.githubusercontent.com/21196400/33231883-7f807ae4-d1f4-11e7-8f17-876cd3464857.png)

Other theme:
![2](https://user-images.githubusercontent.com/21196400/33231884-83aeed62-d1f4-11e7-9f97-a32039d37076.png)

When a high detail background is used:

Greybird:
![3](https://user-images.githubusercontent.com/21196400/33231885-8730eab2-d1f4-11e7-921b-41b05a5e05ee.png)

Other theme:
![4](https://user-images.githubusercontent.com/21196400/33231886-8ab16798-d1f4-11e7-9ac5-e60d81870e3f.png)

**Comment by jEsuSdA** [comment]
Here a workaround that maybe can solve the problem:

Edit your .gtkrc-2.0 file and add this lines:

```
# Iconos transparentes
style "xfdesktop-icon-view" {
XfdesktopIconView::label-alpha = 20
XfdesktopIconView::selected-label-alpha = 100
XfdesktopIconView::ellipsize-icon-labels = 1
XfdesktopIconView::tooltip-size = 128

XfdesktopIconView::shadow-x-offset = 1
XfdesktopIconView::shadow-y-offset = 1
XfdesktopIconView::shadow-color = "#000000"
XfdesktopIconView::selected-shadow-x-offset = 2
XfdesktopIconView::selected-shadow-y-offset = 2
XfdesktopIconView::selected-shadow-color = "#000000"

XfdesktopIconView::cell-spacing = 6
XfdesktopIconView::cell-padding = 6
XfdesktopIconView::cell-text-width-proportion = 2.5

base[NORMAL] = "#000000"
base[SELECTED] = "#000000"
base[ACTIVE] = "#000000"

fg[NORMAL] = "#FFFFFF"
fg[SELECTED] = "#FFFFFF"
fg[ACTIVE] = "#FFFFFF"
}
widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"
```

**Comment by ochosi** [comment]
Hi, I use neither Gnome nor LXDE so I don't support either very actively. What versions of Gnome/LXDE are these?

**Comment by latach** [comment]
Hello, the code above did not work.

I'm using **GNOME Shell 3.26.1** (on ubuntu 17.10). I'm not sure about the LXDE version but it is the one included in xubuntu 17.10.

**Comment by ochosi** [comment]
re: above code: I'm not surprised it didn't work, neither Gnome-shell nor LXDE use xfdesktop...

**Comment by latach** [comment]
I have tried modifying different parts of the code, but I haven't managed to find which lines change the desktop icons text colour. Do you have any idea, kindly?

**Comment by ochosi** [comment]
Sorry, I would have to google/investigate myself and without being able to test, that's tapping in the dark even more than you are.

**Comment by DarkTrick** [comment]
I can't test with the mentioned environments, but perhaps this is fixed now, because we have shadow below  the font?

**Comment by ochosi** [comment]
Let's close this for now. We don't have great support for Gnome Shell and this is actually theming support for an extension. Patches/PRs welcome!
