### ISSUE TITLE
xfce4-fsguard-plugin appearance changed after app update

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#209]
Hi!

I just want to notify xfce4-fsguard-plugin has changed the appearance after last update.

Previous version: 
![captura de pantalla_2017-11-22_18-55-51](https://user-images.githubusercontent.com/5833446/33514505-5aa26046-d755-11e7-8a8d-7324eac2e3ea.png)

Updated version: 
![captura de pantalla_2017-12-02_11-29-00](https://user-images.githubusercontent.com/5833446/33514506-5c209136-d755-11e7-86ba-dad91e828c1c.png)

As you can see, it looks a bit ugly.

I think it could be caused by GTK+3 change, but I don't know.

So, It is possible to solve it or it is necessary to change the gtk theme to support it?

Thanks! ;)

**Comment by ochosi** [comment]
Those are simply different progressbar styles so this difference can be dealt with in Greybird.

**Comment by ochosi** [comment]
Should be fixed with https://github.com/shimmerproject/Greybird/commit/10929b1211b7a3377e1d8bcb2b2b37317b709d82
