### ISSUE TITLE
Chromium / Chrome incognito new tab button is barely visible

### ISSUE THREAD

**Issue by kepler2** [shimmerproject/Greybird#211]
Hello!

First of all, thanks for your work. The theme is very nice, i'm not a big fan of "flat" themes. This theme along with elementary icons make a great desktop :)

I wanted to share an issue:
If you open a new incognito tab in Chrome / Chromium, the new tab button is barely visible. Please see below:

http://i.imgur.com/ZKMzl2f.png

Maybe you can take a look,

Thanks

**Comment by ochosi** [comment]
![screenshot_2018-01-07_00-47-20](https://user-images.githubusercontent.com/261436/34645049-5dc9af08-f344-11e7-9401-060a49569e44.png)

Sorry I can't reproduce that behavior with Chromium 63 on Xubuntu 17.10.

What version are you using?

**Comment by kepler2** [comment]
Hello and happy new year! It seems you are **not** using the GTK theme.

**Comment by ochosi** [comment]
Hm, you're right. Never noticed cause the classic theme looked well integrated enough...

**Comment by ochosi** [comment]
Finally found some reference for Chromium theming, not sure this will also work for Chrome though...
https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_gtk_theme_integration.md

**Comment by kepler2** [comment]
Hello. Here a potential fix? I also reported for Plano theme
https://github.com/lassekongo83/plano-theme/issues/15
https://github.com/lassekongo83/plano-theme/commit/2d51be40085a7c2f832b80f5d6179d959028d9fa

**Comment by ochosi** [comment]
@kepler2 Thanks, I'll pull that in. Does it also work for Chrome or just Chromium (as the code suggests)?

**Comment by ochosi** [comment]
Tested, works for both browsers. Thanks a lot!

**Comment by kepler2** [comment]
Well... I have to thank you. I'll test and get back :)

**Comment by kepler2** [comment]
Thanks, i checked now. The tab button is visible now :)

https://i.imgur.com/4kT6nWQ.png

**Comment by kepler2** [comment]
@ochosi Can you please instruct me on how to modify ass this fix to the integrated greybird theme in Xubuntu (16 LTS)? If I download it from your repository it looks broken (for example in pavuicontrol)

http://i.imgur.com/xzxBt2g.png

Thanks a lot

**Comment by ochosi** [comment]
@kepler2 You have to apply the patch by hand by editing the theme (either as a copy in your ~/.themes directory or directly in /usr/share/themes/Greybird).

in short: 16.04 has a different Gtk+3 version so the latest version of Greybird will not work there.
