### ISSUE TITLE
Nautilus dark theme floating-bar is missing solid background

### ISSUE THREAD

**Issue by slabua** [shimmerproject/Greybird#212]
https://github.com/shimmerproject/Greybird/blob/59322d73ed5fe4337c48959daaf0291955cd68f3/gtk-3.0/_gnome-apps.scss#L13

Could you please enable the solid background and border for the floating-bar in nautilus when using the dark theme? The floating-bar has a solid background already for the light theme but it's transparent in the dark theme.

Currently, it looks like the top half of the attached image, blending with the content of the window.
I edited the css locally to look like the bottom half of it.

![screenshot from 2017-12-17 22-10-25b](https://user-images.githubusercontent.com/1002978/34083952-fda53b2c-e378-11e7-9d93-5bb6e3a73822.png)

**Comment by ochosi** [comment]
Hi, if you've already resolved this locally, why not propose a pull-request? I don't actively maintain the gnome apps part, most of what's there were patches by others as I don't use/test gnome shell myself.

**Comment by slabua** [comment]
@ochosi I will try to have a look at it. Locally, I simply edited the final .css file but on the repository I would need to first understand which source file to edit and how to edit it properly.

**Comment by ochosi** [comment]
You can alternatively post the CSS and I translate it back to SASS for you

**Comment by slabua** [comment]
Hi, thank you, this is the diff to apply to `gtk-3.0/gtk-contained-dark.css`
It's just some nautilus lines copied over from the non dark theme to the dark theme css file.
Probably the colours I used here need some adjustments with the possible new upstream updates.

```
diff --git a/gtk-3.0/gtk-contained-dark.css b/gtk-3.0/gtk-contained-dark.css
index 35d64bb..b30b8dc 100644
--- a/gtk-3.0/gtk-contained-dark.css
+++ b/gtk-3.0/gtk-contained-dark.css
@@ -4363,3 +4363,19 @@ read if you used those and something break with a version upgrade you're on your
 @define-color wm_button_active_color_b shade(#393f3f, 0.89);
 @define-color wm_button_active_color_c shade(#393f3f, 0.9);
 @define-color content_view_bg #292929;
+.floating-bar {
+  background-color: #3b4141;
+  border-style: solid;
+  border-color: #828282; }
+  .floating-bar.left {
+    border-radius: 0 3px 0 0;
+    border-width: 1px 1px 0 0; }
+  .floating-bar.right {
+    border-radius: 3px 0 0 0;
+    border-width: 1px 0 0 1px; }
+  .floating-bar:backdrop {
+    background-color: #3b4141;
+    border-color: #8a8a8a; }
+  .floating-bar button {
+    padding: 0px; }
+
```

**Comment by ochosi** [comment]
Mind to test this branch?
https://github.com/shimmerproject/Greybird/tree/issue212-nautilus-dark-floating-bar

It should have a proper dark floating bar for Nautilus, but also other things.

**Comment by slabua** [comment]
@ochosi thanks, the floating bar looks good to me. Should I test something else in particular?

**Comment by ochosi** [comment]
Wait, I haven't pushed any related changes to the master branch..? So if it works for you in master there's no need for my changes/branch

**Comment by slabua** [comment]
My bad, I confirm that master branch is transparent, whilst issue212-nautilus-dark-floating-bar branch is correctly opaque.
