### ISSUE TITLE
Improve printing dialog

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#216]
Some dialogs, like printing one, are almost white. No grey brackground, a ugly white background on top of tabs, etc.

Maybe it will be great to have a Greybird look fore these windows.

![imagen](https://user-images.githubusercontent.com/5833446/36210843-ce1e78f0-119f-11e8-91fe-bea4eecf74d6.png)

Thanks!!!

**Comment by mrnhmath** [comment]
That's gtk fault, the [gtk3-mushrooms](https://github.com/TomaszGasior/gtk3-mushrooms) patchset restores natural margins that got lost. Nobody reported this issue upstream AFAIK.

**Comment by ochosi** [comment]
@mrnhmath I conclude then that this issue is not in Greybird (feel free to reopen if I misinterpreted your statement).
