### ISSUE TITLE
How to change colors in sidebar

### ISSUE THREAD

**Issue by Stefan-Olt** [shimmerproject/Greybird#221]
Hello,
I would like to change the colors in the sidebar (like the Nemo file manager). I've done this before in Linux Mint 18.x and it was quite easy (I just modified the css files), so it looks like this ("Papierkorb" is mouseover):
![colors_sidebar](https://user-images.githubusercontent.com/9394004/42928516-ccf005a4-8b37-11e8-9642-17905c1a9e04.png)
Unfortunately in Mint 19 the greybird theme is a much newer version and I cannot figure out how to make look like that again, I can change the background color, but whenever the window loses focus it changes back, the text color I cannot figure out all. I tried to replace the entire theme with the old version, but then other stuff breaks like menus.
Any advice?
Best regards
Stefan

**Comment by ochosi** [comment]
Changing the css now is not as straight-forward as it used to be, you're right. The easiest way to go is to clone the theme from git, then modify the scss file/s and run make && make install.

In general, the code for the Gtk3 sidebar is here:
https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/_common.scss#L3632

If you only want to modify the color, it may be most straightforward to change these two values:
https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/_colors.scss#L41
https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/_colors.scss#L66

Note that all of the above changes require you to re-build and -install the theme.

Alternatively you could resort to running sed or something alike on the generated css files, e.g. replacing the hex values for the sidebar color. Sometimes though the color is derived, so this may not work completely reliably.

Hope this helps!
