### ISSUE TITLE
support for sassc as alternative compiler

### ISSUE THREAD

**Issue by ncopa** [shimmerproject/Greybird#222]
the ruby-sass tool is [deprecated](https://github.com/sass/ruby-sass/commit/1571b9b70c4531eeb3aa1090a5b9ecf637319a65#diff-f76a3c73561a24b11078e81ba44dbec0). The new official tool is dart-sass which is implemented in dart. Alpine linux does not have dart (yet) but instead of spending much time on how to port dart to Alpine Linux and musl libc, it would be so much eaiser if sassc could be used as an alternative.

**Comment by ochosi** [comment]
Yeah, makes sense to me.
I had a local patch for this already at some point, I'll try to dig it up or re-do it.

**Comment by ochosi** [comment]
Ok, I have a working patch now. However, some colors are interpreted differently by sassc (I still have to look which operations exactly) so I wanna check why this is or how to fix it before I push it.
