### ISSUE TITLE
Xfwm 4.13.1 tabwin as list too sparse

### ISSUE THREAD

**Issue by andreldm** [shimmerproject/Greybird#224]
Until now Xfwm 4.13.1 tabwin was missing proper Greybird style, it looks great when using the default icon mode, but when "Cycle through windows in a list" is enabled in Window Manager Tweaks, it looks too sparse:

![image](https://user-images.githubusercontent.com/599565/44375675-43f13e00-a4cb-11e8-9765-ff3c240c53b2.png)

**Comment by ochosi** [comment]
Oh my, I guess I would have to patch Xfwm4 to properly fix this...

Currently there is no meaningful way to distinguish the list and the normal style, at least not in CSS. I will take a look at Xfwm4 I guess.

**Comment by andreldm** [comment]
I don't think so, you just forgot about `listview-icon-size`, all you need to do is to add `-XfwmTabwinWidget-listview-icon-size: 24px;` to `#xfwm-tabwin`.

**Comment by andreldm** [comment]
Oh, `min-width` and `min-height` in `#xfwm-tabwin button` need to be removed or decreased to 24px.

**Comment by ochosi** [comment]
Yeah, I know and that's not a very nice solution. It would be nicer if Xfwm4 would set an additional styleclass dynamically when the list mode is in use

**Comment by andreldm** [comment]
Upstream bug: https://bugzilla.xfce.org/show_bug.cgi?id=14635

**Comment by ochosi** [comment]
Until we get this fixed in Xfwm4 I don't want to leave everyone using Xfwm4 with listview and Greybird in the rain. I can always re-introduce this style again later.

**Comment by andreldm** [comment]
That patch landed in xfwm4 master:
https://git.xfce.org/xfce/xfwm4/commit/?id=66e742dcd2ffee961f4e75d0f4a7fec329d70337

**Comment by ochosi** [comment]
Thanks @andreldm, I'll take a look at this again soon.

**Comment by ochosi** [comment]
Works nicely with git master! Thanks for the patch.
