### ISSUE TITLE
No Tabs in Thunderbird

### ISSUE THREAD

**Issue by Axics** [shimmerproject/Greybird#237]
When I use the latest version of Greybird (3.22.9) the tabs in Thuderbird are not displayed correctly.
![issue_thunderbird](https://user-images.githubusercontent.com/42804310/46784774-b940f880-cd2f-11e8-867e-c2927934b1e9.png)
The correct representation should be
![issue_thunderbird_right](https://user-images.githubusercontent.com/42804310/46785110-0d001180-cd31-11e8-82bc-9a0e4049dd9d.png)

**Comment by ochosi** [comment]
Not sure what to do about this as Firefox doesn't use Gtk+ directly, it just tries to render its widgets in a way that mimicks Gtk+.
If this is still Gtk+2 then I guess the murrine engine may be at fault. If it's Gtk+3 then I'm not sure what about my tab style it doesn't like.

Do any other themes also expose this bug?

**Comment by andrei-a-papou** [comment]
@ochosi no, the GTK2 version of Thunderbird doesn't have this problem. This applies only to GTK3. 

In Firefox, this is rarely seen (as the broken tabs are only used under the _View Certificate_ dialog). But in Thunderbird it makes the _Preferences_ window almost unusable, as TB uses those tabs all over the place.

**Comment by jEsuSdA** [comment]
@ochosi there is some GTK+ styles that are applied to Firefox and Thunderbird.
For example, I added this code to greybird css 

`
separator { color: #e3e3e3;}
`
To avoid black lines separators in Thunderbird and Firefox popup menu.

I mean, maybe it would be possible to solve the Thunderbird tabs bug using GTK+ CSS rules.

**Comment by andrei-a-papou** [comment]
after some fiddling with userChrome.css, turns out it's possible to fix it on the Thunderbird end.

![image](https://user-images.githubusercontent.com/30468319/47278517-5cb4c780-d5d2-11e8-9fe1-2f9093306e9b.png)

**Comment by stefson** [comment]
Can you please share these css tweaks?

**Comment by andrei-a-papou** [comment]
@stefson Sure, I was going to, just needed to tweak the backgroundof inactive tabs a bit. Put the code below into your chrome/userChrome.css and restart Thunderbird.

`/* fix broken GTK3 tabs in some dialog windows */
#MailPreferences tab,
#certmanager tab,
#certDetails tab {
    -moz-appearance: none !important;
    box-sizing: content-box !important;

    background-color: #C1C1C1 !important;

    border-style: solid !important;
    border-width: 1px !important;
    border-bottom-width: 0 !important;
    border-color: #9C9C9C !important;

    margin: 2px 0 0 1px !important;
    padding: 5px 12px !important;
}

#MailPreferences tab[selected="true"],
#MailPreferences tab[visuallyselected="true"],
#certmanager tab[selected="true"],
#certmanager tab[visuallyselected="true"],
#certDetails tab[selected="true"],
#certDetails tab[visuallyselected="true"] {
    -moz-appearance: none !important;
    box-sizing: content-box !important;

    background-color: #CECECE !important;

    border-top: 3px #398EE7 solid !important;
    border-bottom: 1px #CECECE solid !important;
    border-left-color: #7F7F7F !important;
    border-right-color: #7F7F7F !important;

    margin-bottom: -1px !important;
    margin-top: 0 !important;
    padding-bottom: 6px !important;
}

#MailPreferences tab + tab,
#certmanager tab + tab,
#certDetails tab + tab {
    -moz-appearance: none !important;
    box-sizing: content-box !important;
    margin-left: -1px !important;
}

#MailPreferences tabs + tabpanels,
#certmanager tabs + tabpanels,
#certDetails tabs + tabpanels {
    -moz-appearance: none !important;
    border: 1px #7F7F7F solid !important;
}
`

Result:

![image](https://user-images.githubusercontent.com/30468319/47532266-89116200-d8b8-11e8-8a9d-ccb0a965395d.png)

**Comment by jEsuSdA** [comment]
Thanks a lot!! ;)

**Comment by andrei-a-papou** [comment]
@jEsuSdA you are welcome :) Updated the code and screenshot above to reflect the final version I've settled for.

**Comment by jobisoft** [comment]
Is there any way to include this fix so that users do not have to apply it on themself? It does happen on all Linux, just some like XFCE. Is that a bug in Thunderbird?

**Comment by bluesabre** [comment]
Thunderbird 68 (maybe earlier) replaced the preferences dialog with a web-based one, and now the tabs are drawn by the browser. See the below screenshot.

![Screenshot_2019-11-03_21-30-12](https://user-images.githubusercontent.com/1894517/68096825-5877e700-fe81-11e9-9591-c6ca244f6bc4.png)

As a result, these changes should not longer be needed.

**Comment by andrei-a-papou** [comment]
In Firefox (which also has a web-based prefs window) there's also a GTK+ _View Certificate_ dialog that uses tabs. I don't have Thunderbird 68+, so I can't check. But it very well may be the same with TB.

**Comment by Axics** [comment]
As mentioned before, Thunderbird has replaced the settings dialog with a web-based one. So this works now :)
