### ISSUE TITLE
[Suggestion] CSS to improve the Print Dialog and Tabs

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#238]
Here some CSS lines to improve the Print Dialog appearance for your consideration:

```
printdialog > box
{
	background-color:#cecece;
}

printdialog box.vertical
{
	background:#cecece;
}

```

And here, some CSS lines to get back again the Greybird famous gradient to Tabs

```
tab
{
  background-image: linear-gradient(to bottom, shade(shade(#cecece, 1.02), 1.05), shade(shade(#cecece, 1.02), 0.97));
}

tab:checked
{
background-image: linear-gradient(to bottom, shade(shade(#cecece, 1.02), 1.05), shade(shade(#d9d9d9, 1.02), 0.97));
}
```

From this:

![imagen](https://user-images.githubusercontent.com/5833446/46863333-6d697e80-ce17-11e8-9ea2-a38324598ddf.png)

To this

![imagen](https://user-images.githubusercontent.com/5833446/46863571-2039dc80-ce18-11e8-83a8-167f7394697b.png)

**Comment by ochosi** [comment]
Thanks for the hint. I pushed a slightly different fix, but the result is the same.

**Comment by jEsuSdA** [comment]
Thanks a lot, @ochosi ! ;)
