### ISSUE TITLE
Google Chrome window control buttons

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#239]
Window control buttons of greybird are displayed differently in Google Chrome (as seen in the screenshot below showing it together with Firefox window).
Actually even the top of the window border (as there's no titlebar in this case) looks also different (completely flat) but  it's not a big thing es pecially compared to those buttons.
![selection_2018-10-16-11 56 40](https://user-images.githubusercontent.com/6375934/47005757-19bfa380-d13d-11e8-90f5-6e0da54951db.jpg)
**system:** linux mint 19 cinnamon
**greybird-gtk-theme:** 3.22.8-1 (from ubuntu)

**Comment by ochosi** [comment]
This has been fixed in 3.22.9
