### ISSUE TITLE
VSCode dialogs don't display properly with Greybird.

### ISSUE THREAD

**Issue by nawordar** [shimmerproject/Greybird#242]
When I open a dialog in VSCode, it displays like this: 
![open file dialog](https://user-images.githubusercontent.com/26769700/51983168-44d5c500-2498-11e9-87a5-4829868b0ba5.png)
I tried symlinking /usr/share/themes/Greybird to /home/nawordar/.themes/Greybird without success.
Other themes work just fine:
![numix](https://user-images.githubusercontent.com/26769700/51983600-5ff50480-2499-11e9-8b63-094f5b75bc20.png)

**Comment by ochosi** [comment]
Looks a bit as if you had an old version of Greybird or some other problem with your installation. I'm pretty confident it's not a theme issue.

**Comment by ochosi** [comment]
In any case, what distro, what version of VSCode and how did you install it / where did you get it from?

**Comment by nawordar** [comment]
@ochosi Well, you were right. I had snap version installed from Software Centre and after installing version from official Microsoft repository, everything started working fine. I'm closing the issue.

**Comment by jbicha** [comment]
@nawordar The Snap issue is being tracked at https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/7 Hopefully that will be fixed soon and you can go back to use the Snap version if you want.
