### ISSUE TITLE
Print Dialog missmatch when inactive 

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#243]
Hi!

I notice the print dialog changes the background color when inactive and this is what it looks:

![imagen](https://user-images.githubusercontent.com/5833446/55095876-3206f780-50b9-11e9-9a20-acfe7d37dac4.png)

Is there any way to add any CSS class to make the print dialog having same colors when active and inactive?

Thanks a lot!

Related with 
https://github.com/shimmerproject/Greybird/issues/238

**Comment by ochosi** [comment]
Thanks for noticing, fixed.
