### ISSUE TITLE
Install separate "Greybird-dark" theme

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/Greybird#253]
Since Greybird already has dark styles, let's consider building and installing a separate "Greybird-dark" theme. This follows Adwaita, which also ships a "-dark" variant, and should it be considered (or made) a standard, this could be used as an alternative path to Xfce "dark modes".

**Comment by Mau-G** [comment]
@bluesabre we already did that change with greybird-geeko: https://github.com/shimmerproject/Greybird-Geeko

We @shimmerproject/opensuse can help with that but we changed buildsystem to meson and it's mandatory for the proper split of the theme. As long as you and other packagers are ok with this the port would be relatively simple for us to do .

**Comment by bluesabre** [comment]
Resolved with #256
