### ISSUE TITLE
GNOME Builder's GtkHeaderBar is too big

### ISSUE THREAD

**Issue by MahmoudKhalil** [shimmerproject/Greybird#264]
![builder](https://user-images.githubusercontent.com/9035341/77818920-4cfeb400-70df-11ea-8e93-f79a15dc0f83.png)

**Comment by andreldm** [comment]
That's a problem caused by this [`min-height: 28px;`](https://github.com/shimmerproject/Greybird/blob/55c7a77386e440523b4b9bdc27dd4d553f2f8c52/light/gtk-3.0/_common.scss#L1595) declaration.

**Comment by MahmoudKhalil** [comment]
Hi @andreldm,

Really sorry for the late reply, for some reason I didn't see the notification on my mail.
What do you recommend in this case? should I tinker and play with it a little and make a MR for it?

**Comment by andreldm** [comment]
@MahmoudKhalil, no problem, we are not in a hurry :smile: 
Yes, do please try to put together a pull request, although I think the solution is not just to lower that min-height, maybe a different value can be set only for gnome builder.

**Comment by ochosi** [comment]
This worked for me when debugging Gnome Builder in GtkInspector
`headerbar entry button image { min-height: 12px; padding: 0; }`

**Comment by andreldm** [comment]
That works for me:
![image](https://user-images.githubusercontent.com/599565/100031426-640fb600-2dd4-11eb-8d5a-2bc009efe28d.png)

I'd try to put together a pull request, but I'm not sure where to stick into `_common.scss` :sweat_smile:
