### ISSUE TITLE
Greybird-dark titlebar hardly readable with the text shadow

### ISSUE THREAD

**Issue by kiskoza** [shimmerproject/Greybird#267]
Hi!

I made a fresh Xubuntu 20.04 install and chose the Greybird-dark theme. Now all my titlebars has a text shadow, which makes them hardly readable. Is there a way to flatten it?

![image](https://user-images.githubusercontent.com/1900366/80528809-d03d4f00-8996-11ea-8970-835d3feb0a50.png)

```
$ dpkg -l | grep greybird
ii  greybird-gtk-theme  3.22.12-0ubuntu1  all  grey GTK+ theme from the Shimmer Project

$ xfce4-about --version
xfce4-about 4.14.1 (Xfce 4.14)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by nicokaiser** [comment]
This is the Greybird-dark GTK theme with the Greybird (not dark) Xfwm4 theme. You need to set Xfwm4 to also use the Greybird-dark theme, then it looks great. Unfortunately, in Xubuntu this does not work automatically, you need to select the theme in the "xfwm4-settings" app.

**Comment by kiskoza** [comment]
Thank you very much, that was the issue with my setup
