### ISSUE TITLE
Xubuntu 20.04 - Theme badly broken in VirtualBox

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [shimmerproject/Greybird#268]
it looks broken in every theme, not just greybird
![Screenshot_2020-05-10_18-46-00](https://user-images.githubusercontent.com/564653/81515907-17ff9700-9304-11ea-803c-fac4c4b9772e.png)
![Screenshot_2020-05-10_18-45-28](https://user-images.githubusercontent.com/564653/81515912-1afa8780-9304-11ea-8290-b3acabed417d.png)

**Comment by m4u9** [comment]
i’m sorry to close this but it’s not a theme issue. Please report it to virtualbox instead

**Comment by GM-Script-Writer-62850** [comment]
Really!? Found an existing report: https://www.virtualbox.org/ticket/18258

**Comment by m4u9** [comment]
I meant it's not an issue we can fix here. Also this theme is for GTK and VBox gui is based on Qt.
