### ISSUE TITLE
Dark theme on xfce

### ISSUE THREAD

**Issue by wsalmeida** [shimmerproject/Greybird#269]
Using tem dark in debian stable I noticed that the font colors are dark on the xfce panel it seems incompatible.

**Comment by m4u9** [comment]
what version of Xfce and greybird is Debian using?

**Comment by sashaaaaaaaaa** [comment]
Same using Greybird 3.22.12 and Xfce 4.12 on Slackware-current.

**Comment by sashaaaaaaaaa** [comment]
Also the titlebar text is dark too.

**Comment by sashaaaaaaaaa** [comment]
Updating to Xfce 4.14 I see fixed that. So it might be incompatible with 4.12.

**Comment by ochosi** [comment]
Yes, quite possibly. I don't test Greybird anymore against the 4.12 version of the xfce4-panel.
(Background: in 4.12 the panel was Gtk2 and the plugins were both Gtk2 and Gtk3. In 4.14 the panel was Gtk3 and the plugins were Gtk2 and Gtk3. In 4.16 only Gtk3 is left.)
