### ISSUE TITLE
Missing edge on the button

### ISSUE THREAD

**Issue by remussatala** [shimmerproject/Greybird#270]
Look here:
https://drive.google.com/file/d/1kJeghGl02IKEzYgPTyLqwRKNptEF88VW/view?usp=sharing
https://drive.google.com/file/d/1Gh_Zi12UDw8J671HUWBbRWgr4Trk50kR/view?usp=sharing
https://drive.google.com/file/d/14G3Q_vGiDj1kN6hJ1je11C8N0lf1SXLW/view?usp=sharing

**Comment by birdie-github** [comment]
already reported in #265

**Comment by andreldm** [comment]
Yes, dup of #265
