### ISSUE TITLE
Kvantum theme for Qt softwares

### ISSUE THREAD

**Issue by apandada1** [shimmerproject/Greybird#273]
The greybird project looks great, but does not have a similar theme for softwares made with Qt. 
If a Kvantum theme for Greybird is made, that can be used to give a uniform look for GTK and Qt apps in XFCE desktop.

**Comment by ochosi** [comment]
Hi, this is not a bug in the Gtk theme but a problem in your setup. Depending on your distribution the package for Qt theme support will be called differently, maybe best to Google for it... In the past it used to be called something like qt4-config...
