### ISSUE TITLE
disable "hide scrollbar" function

### ISSUE THREAD

**Issue by Golddouble** [shimmerproject/Greybird#275]
In thunar:
When I do not move the mouse, then the scrollbar is hidden at the right and at the bottom.

Question:
Is there a way to change the theme by my self, so that the sliders not longer hides, so that it is the same as it is in Featherpad.

Can you pleas say me, which code fragments I have to change?

Thank you.

**Comment by ochosi** [comment]
This is not a theme setting, but a gsetting. Here's a blog post that explains how it's done: https://www.linuxuprising.com/2019/09/how-to-disable-gnomes-overlay.html
