### ISSUE TITLE
Colour of the title bar

### ISSUE THREAD

**Issue by Golddouble** [shimmerproject/Greybird#277]
I would like to have different colours in the title bar for GTK2 and GTK3 Apps. So that when I am working, I can immediately see whether I am in a GTK2 or GTK3 program.

Can you please say me, which code fragments I have to change for this?

Thank you very much.

**Comment by ochosi** [comment]
The colors of the xfwm4 theme depend on background and foreground colors of the Gtk theme, so you would have to generally alter the look of the two toolkit variants.

Alternatively you can set GTK_CSD=1 in your session and use an xfwm4 theme that is not Greybird. Then I guess all Gtk2 apps would still get SSD (from xfwm4) and all Gtk3 apps would get CSD. (Untested)

**Comment by Golddouble** [comment]
> The colors of the xfwm4 theme depend on background and foreground colors of the Gtk theme ...

I understand, that in this case I must for example change some colours in the GTK2 theme and after I will have different colours in the title bar in GTK2 and GTK3 apps. Right?

Can you please say me the code fragment, where I can find this colour(s)? Thank you.
