### ISSUE TITLE
Greybird-dark does not look good

### ISSUE THREAD

**Issue by Golddouble** [shimmerproject/Greybird#280]
Here you can see how it looks on my system:
![greybird dark](https://user-images.githubusercontent.com/13977359/85946099-497b0300-b942-11ea-80dc-2033753ac1c9.png)

As you can see in the left section: Only the VM I have selected shows its name. The other above do not show there names, because the background and the font have the same colour.

**Comment by m4u9** [comment]
Virtualbox uses the Qt toolkit. This problem is due to poor Qt integration. Because Greybird is a GTK theme, we can't fix this from our side. I suggest you report this to Virtual Box instead since it affects other GTK themes too.

**Comment by Golddouble** [comment]
Thank you.

What do you mean with QT toolkit?
Do you mean this one:
![qt toolkit](https://user-images.githubusercontent.com/13977359/86124569-a8c04b00-badb-11ea-93bf-d9d6e48e4357.png)




If yes: Do you trying to say, that Virtual Box has a poor qt5ct integration or do you try to say, that qt5ct is bad integrated into my Linux distribution?

Thank you.
