### ISSUE TITLE
Can't see memory usage in Task Manager in dark theme

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/Greybird#281]
The red color used for memory in Task Manager is difficult to see when using Greybird dark.
![image](https://user-images.githubusercontent.com/4412114/87251236-31939b00-c47b-11ea-96d0-0210ec9c8479.png)

Filed upstream as well.
https://gitlab.xfce.org/apps/xfce4-taskmanager/-/issues/26

**Comment by ochosi** [comment]
The upstream issue is fine, this is a problem that would have to be fixed in task manager (this color is currently hardcoded)
