### ISSUE TITLE
Problems with some buttons and some comparisons

### ISSUE THREAD

**Issue by remussatala** [shimmerproject/Greybird#299]
Here you can find a video capture with Greybird 3.22.14 in Arch Linux:
http://s.go.ro/3dsj8eun

**Comment by ochosi** [comment]
Are you using some noCSD patch?
Also, what application is this?

**Comment by remussatala** [comment]
Yes, a few repairs have been made lately and now everything is like in the good old days.
More details can be found here:
https://github.com/ZaWertun/gtk3-nocsd
https://aur.archlinux.org/packages/gtk3-nocsd-git

**Comment by ochosi** [comment]
Don't expect the CSD theming to work with nonCSD patches. As I'm not using such a patch myself I won't work on fixing issues that come up with it.
