### ISSUE TITLE
Make xfwm4 theme look like CSD windows theme

### ISSUE THREAD

**Issue by leandroramos** [shimmerproject/Greybird#301]
It would be nice if the XFWM4 borders theme looked like the CSD windows theme, with dark border instead of the current light border.

![greybird-dark](https://user-images.githubusercontent.com/3253741/130336084-b1d264c3-7c6e-4742-943d-5bf1a6497a02.png)

Here are the proposed changes:

![greybird-dark-xfwm4-dark-border](https://user-images.githubusercontent.com/3253741/130336105-136ba7c1-56ab-4471-98bc-8ff1fef39818.png)

Thank you for this theme :)

**Comment by ochosi** [comment]
It would be nice if you could refer to the issue you're fixing in your next PR. Only noticed now that the one I just merged was about this issue...
Closing as fixed by #302
