### ISSUE TITLE
Latest Release(s) xfce-notify - colors changed?

### ISSUE THREAD

**Issue by 0pLuS0** [shimmerproject/Greybird#315]
Hello,

I found online a rpm at a repo for what I believe is an older version you did, greybird-3.22.12-1. 

Using xfce4-notifyd-0.6.2, one thing I'm noticing with themes I can find online, the lower right corner of the OSD theme, the right corners aren't round, you can make out slightly, that they have normal straight corners.

I hope you can fix this corner issue I keep running into.

If you look real close, you'll see the different color and straight edges of the bottom right. You might need to download it, so you can zoom it.

![right_corner](https://user-images.githubusercontent.com/36190223/157570028-62e1ea2c-5515-4352-bb56-4fc26a88740e.jpg)

Here's the greybird-3.22.12-1 theme I found online.

[gtk.css.txt](https://github.com/shimmerproject/Greybird/files/8219498/gtk.css.txt)

Did you change the colors of the latest version? Here's a screen shot of the theme I found in the Greybird-3.22.15/light directory.

Also with a lot of the themes I am seeing, the Button has a white line across the top, it's not all solid color. The bottom right also has a little bit of a pointed/straight edged corner too, but it's smaller and not as noticeable.

![greybird](https://user-images.githubusercontent.com/36190223/157572721-e04db8df-2cfd-4159-96ea-4bcd8ef45b8e.jpg)

Thank you very much for your time and consideration in making xfce-notify themes.

**Comment by ochosi** [comment]
Hi! This is what it looks like with the latest release
![image](https://user-images.githubusercontent.com/261436/162388699-6dd3edd8-b8fc-4d1e-a4d4-ccc7738e2917.png)

**Comment by ochosi** [comment]
FWIW if you're using 'Greybird' as your Gtk theme there is no need to set it in xfce4-notifyd, you can just leave it at 'Default'.

**Comment by 0pLuS0** [comment]
There is no ```Default``` I pick the them I want to use, all the names are displayed, not sure what you mean by a Default.

**Comment by ochosi** [comment]
The `Default` tries to just use the colors/theming options from the currently selected Gtk theme (in Xfce via Appearance Settings).
![image](https://user-images.githubusercontent.com/261436/163566396-cdd63aa7-fc47-48c3-bb20-9a35c5e8fd21.png)

**Comment by 0pLuS0** [comment]
I don't have Default in Slackware, maybe because I compiled this myself, and Default is tied to a precompiled package for a Distro or Xfce.

Anyhow it seems to be working ok now, the colors, but as I pointed out, the corners aren't getting rounded 100% completly smooth.

THANKS

**Comment by ochosi** [comment]
If you don't use compositing with your window manager the corners won't be rounded because notifyd doesn't use the XShape extension in these cases.

Anyway, closing this as it seems everything in Greybird works as it should.

**Comment by 0pLuS0** [comment]
I do use compositing, I'm using picom, even with picom I'm getting this.

https://github.com/yshui/picom

But what I can tell you, is that I don't see this happening with all of the themes, only some of them.

THANKS

**Comment by 0pLuS0** [comment]
This is the only section I can think for picom effects rounded corners, but I commented it out, and I still see the corner. So I'm not sure what to do with this? Hmm

```# Exclude conditions for rounded corners.
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];```
