### ISSUE TITLE
Make task switcher with image preview bigger

### ISSUE THREAD

**Issue by huyhoang8398** [shimmerproject/Greybird#324]
I would suggest to make the task switcher a little bigger for easier to use.

- Bellow is the current greybird-dark task switcher, it is really small in big screen
![image](https://user-images.githubusercontent.com/25379882/183536111-470b2b0e-61f2-4955-a8ce-bd9864d9b035.png)

- Bellow is Adwaita theme task switcher verry big and easier to use
![image](https://user-images.githubusercontent.com/25379882/183536231-98fe550c-e67b-41dc-8e70-519724501be7.png)

**Comment by Mel34** [comment]
Workaround is to put this snippet in gtk.css
`~ ▶ cat .config/gtk-3.0/gtk.css 
/* Xfwm4's alt-tab dialog, aka "tabwin" */
#xfwm-tabwin { -XfwmTabwinWidget-preview-size: 256px; }`
Would be nice if it were bigger by default.

**Comment by ochosi** [comment]
Yeah, I guess bumping the size makes sense. I've doubled it from 64 to 128, hope that strikes a good middle ground for everyone.
