### ISSUE TITLE
xfdesktop 4.19.0 - Icon-label color not transparent when other window is focused

### ISSUE THREAD

**Issue by alexxcons** [shimmerproject/Greybird#336]
Xfdesktop has focus:

![Bildschirmfoto_2023-02-02_16-32-19](https://user-images.githubusercontent.com/2205293/216370527-10802907-0f69-4bbc-8a88-4cdc39eac15c.png)

Some other window has focus:

![Bildschirmfoto_2023-02-02_16-31-54](https://user-images.githubusercontent.com/2205293/216370523-a8475c7c-95b4-4aea-ba0a-c54db73c2e96.png)

(Similar for greybird-dark)

I suppose this commit is related (though might not be the trigger of the original change): https://gitlab.xfce.org/xfce/xfdesktop/-/commit/6d991e6845966f69bc491055fcaf7c60a6123987

iirc, before the background-color was just fixed to transparent by xfdesktop, while now it is theme-specific (please correct me if I am wrong)

**Comment by alexxcons** [comment]
@kelnos  hope it's correct this way ?  I failed to find the relevant commit/issue in the xfdesktop gitlog.

**Comment by kelnos** [comment]
Yeah, looks right to me.

**Comment by andreldm** [comment]
I don't think that commit caused this issue, that is a fallback style, with Greybird that is not applied.

Anyway, please review and test: https://github.com/shimmerproject/Greybird/pull/338

**Comment by alexxcons** [comment]
Nice @andreldm !  

Just tried to build stuff from master to test this, but failed for ./autogen.sh on xfdesktop:

```
./configure: line 19302: syntax error near unexpected token `X11,'
./configure: line 19302: `XDT_CHECK_OPTIONAL_FEATURE(X11,'
```
xfce4-dev-tools is up-to date ... any idea @kelnos  ?

So I went back to xfdesktop 4.19.0 ... for which cannot reproduce the bug anymore (without having this MR applied yet :unamused: ) ... will try a re-login now .. who knows

**Comment by kelnos** [comment]
@alexxcons you need xfce4-dev-tools 4.19.0.  If you have it installed outside `/usr`, then you need to set `XDT_PROG_AUTORECONF='autoreconf -I /other/prefix/share/aclocal'`.

(Maybe `xdt-autogen` should automatically add to the include path if it's installed outside autoconf's prefix...)

**Comment by alexxcons** [comment]
I did not provide a prefix for xfce4-dev-tools, it installed into `/usr` (stuff was installed to` /usr/local/bin`).   Just tried with dev-tools 4.19.0 instead of master, but same result.

Hum, suppose I need to figure out where that `X11` is supposed to come from.

**Comment by alexxcons** [comment]
Hmm, looks like something is broken on my autohell setup :/  

When I add `AC_CONFIG_MACRO_DIRS([/usr/local/share/aclocal])` to configure.ac, the relevant m4 files are found again. So I suppose that my default m4 lookup path is wrong/incomplete for whatever reason.

**Comment by kelnos** [comment]
I think that's expected.  `/usr/local` _is_ a nonstandard prefix; autoconf only looks in `/usr/share/aclocal`.  So `XDT_PROG_AUTORECONF='autoreconf -I /usr/local/share/aclocal'` would probably work as well.

**Comment by rworkman** [comment]
EDIT (redacted the now-irrelevant info): 7e4507d7713b2aaf41f8cfef2a1a9e214a4d8b6f in Greybird git fixes this.
