### ISSUE TITLE
Xfwm4: single pixel resize borders are unusable

### ISSUE THREAD

**Issue by achadwick** [shimmerproject/Greybird#51]
Single pixel resize borders cannot be used with the mouse without - by definition - pixel precise mouse pointer placement by the user. This lack of forgiveness here is a problem for usability, but this is perhaps only a major problem for us Xfwm users.

The problem is worse with a graphics tablet - those frequently have a lot of subpixel jitter due to hand movement. Frequently, pen input users cannot use the Alt key to resize windows either - that's something that requires a physical keyboard.

The problem is worse in Xfwm than in other WMs and DEs because Xfwm does not currently offer additional "magic" border resize space outside the window when the window has focus (examples: Unity, Gnome, Cinnamon). I would be fine with Greybird and Numix looking slightly different across different WMs, because each WM has different features and drawbacks. I would expect a theme to respect that.

I have aesthetic concerns as well as practicality concerns about the 1px borders in Numix (https://github.com/shimmerproject/Numix/issues/100), but they admittedly look much prettier in Greybird. They still make resizing tricky though.

Perhaps for Greybird!Xfwm we could compromise on a NeXT-style bottom resize bar? I think that might be rather in keeping with the theme's ethos. Those can be made to look pretty, and are easily grabbed.

**Comment by Yanpas** [comment]
:+1:

**Comment by Yanpas** [comment]
@achadwick Mint-X theme has theme for xfwm4, it's looks exactly like greybird, but borders are wider
