### ISSUE TITLE
Restore old titile & button border in metacity 

### ISSUE THREAD

**Issue by khurshid-alam** [shimmerproject/Greybird#54]
I like greybird window control & I use it with other themes as well.

But, In recent version of greybird (from trusty repo) started using large size (4) tile & button border. This is causing visual glitches in window controls area. It looks very odd.

Screenshot:
![greybird tile & button border](http://i.imgur.com/njQ9uFz.png)

Earliar it was using 

```
<border name="title_border" left="8" right="8" top="2" bottom="2" />
<border name="button_border" left="0" right="0" top="0" bottom="0" />

```

& now it is

```
<border name="title_border" left="8" right="8" top="4" bottom="4" />
<border name="button_border" left="0" right="0" top="4" bottom="4" />

```

Please restore it back to old one.

**Comment by ochosi** [comment]
I don't expect that this will ever get fixed, because Satyajit implied that it can't. Closing the issue.
