### ISSUE TITLE
Borders in GTK3 toolbar icons

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#69]
Hi!,

In recent gtk update a ugly borders has appeared in toolbars icons, converting they in buttons.

See the image: top window ( the ugly toolbars icons converted to buttons ), bottom window ( GTK2 appearance. GTK3 before update looks like identical):

![screenshot30](https://cloud.githubusercontent.com/assets/5833446/4591125/3f6ea1da-5068-11e4-8012-295f97a825e0.png)

**Comment by ochosi** [comment]
The checked state is all there now and toolbar icons should look as they should again. Please upgrade and feel free to reopen if you still encounter problems.
