### ISSUE TITLE
unsightly dropdown menu borders with latest GTK3

### ISSUE THREAD

**Issue by tambeta** [shimmerproject/Greybird#72]
Upgrading to the latest GTK3 seems to have caused (likely unintentional) fuzzy borders to appear on dropdown menus in GTK3 apps with the Greybird theme. With underlying GTK 3.14.5, this issue is present in both Greybird 1.3.4 and 1.4. I did not notice this issue with GTK 3.12.2 + Greybird 1.3.4. Examples (GB 1.4, GTK 2.24.25, GTK 3.14.5):

* [GTK2 app (Pidgin), no menu border](http://i.imgur.com/TGRyH6v.png)
* [GTK3 app (gnome-terminal), fuzzy border](http://i.imgur.com/9dgebIz.png)

**Comment by ochosi** [comment]
I've fixed this in the most recent release, please upgrade and test and comment if you still encounter this issue. Closing meanwhile.
