### ISSUE TITLE
Gtk3 (3.14) - Statusbar shows border

### ISSUE THREAD

**Issue by Schoelje** [shimmerproject/Greybird#73]
In Debian (tracking Jessie), with Xfce and libgtk-3-0 version 3.14.5-1 the statusbar shows a border in Gtk3 applications and padding also seems different from Gtk2 applications.

![greybird-gtk3-statusbar](https://cloud.githubusercontent.com/assets/2048535/5327954/c49c85a8-7d67-11e4-89c3-654daded3353.png)

I've been playing around with the Statusbar section* in gtk-widgets.css but any change I made did not show up in the application.

I know that you do not support 3.14 or higher, but I thought I should mention it.

*) This is the code section I referred to:
GtkStatusbar {
    padding: 3px;
    color: @theme_fg_color;
}

**Comment by ochosi** [comment]
Can you reproduce this issue with the latest version of Greybird? I've just released 1.5 which should support Gtk3.14 just fine.

**Comment by Schoelje** [comment]
My aplogies for getting back this late. I've been rather busy with the transition to Debian Jessie. Yesterday I checked with your latest version and all looks good. 

I just cannot find the code to darken the shades of the scrollbar slider (not the stepper, that was easy to change). I'm using a light theme and now the scrollbar is just as white as the background (no shades). 

As for this issue: solved and can be closed.
