### ISSUE TITLE
xfce4-panel - systray - checkboxes

### ISSUE THREAD

**Issue by cinquecento** [shimmerproject/Greybird#75]
Maestro Ochosi, is it by design intended checkbox absence as part of xfce4-panel systray menus, in latest commits?

poma

**Comment by ochosi** [comment]
Invece no. Allora, mostrami un esempio/testcase, per favore!

(What I presume is going on is you're seeing problems with Gtk3, so maybe there is a mismatch between the Greybird and Gtk3 version you're using.)

**Comment by cinquecento** [comment]
Eccola, 
http://goo.gl/MtsMnz

**Comment by ochosi** [comment]
Hm, sorry, but with this amount of screenshots I'm a bit confused. The red ones look ok and that's how it should be with latest git master on Gtk3.14. Could you clarify that a bit?

**Comment by cinquecento** [comment]
Maestro Ochosi, according to what you've written I can conclude, checkbox absence as part of xfce4-panel systray menus *is* by design intended.

My idea is *not* to *exclude* checkboxes as part of xfce4-panel systray menus, the same way that they are *included* in *all* the other dialog boxes/windows.

**Comment by ochosi** [comment]
I understand. That won't happen though. In Gtk2 menus there are no indicators of unchecked checkboxes either and that cannot be changed (Gtk2 is not as flexible as Gtk3) so this would lead to inconsistency, which I don't want. So the status quo is going to remain as it is, sorry.

**Comment by cinquecento** [comment]
Maestro Ochosi, if possible I would appreciate clearer explanation.
Namely, whether they are checked  or unchecked, checkboxes are always present in GTK+ 2.

**Comment by ochosi** [comment]
Check a Gtk2 application of your choosing, e.g. Thunar. Open e.g. the View menu, see the "Statusbar" and "Menubar" entries. Those are checkboxes. If they're not active, nothing is shown. That's the default behavior in Gtk2 menus (and in Gtk3 too, check Adwaita for reference).

**Comment by cinquecento** [comment]
I tested with Thunar and xfce4-terminal.

Herewith, solely GTK+ 2 themes, constant presence of checkboxes *is* achieved:
Clearlooks         (gtk2-engines & openbox)
ClearlooksClassic  (gnome-themes)
Darklooks          (gnome-themes-extras)
Glider             (gnome-themes)
Glossy             (gnome-themes)
Industrial         (gtk2-engines)
Mist               (gtk2-engines)
Nodoka             (nodoka-filesystem)
QtCurve            (qtcurve-gtk2)
ThinIce            (gtk2-engines)
Unity              (gnome-themes-extras)

However with other GTK+ 2 / GTK+ 3 combined themes, presence of checkboxes *is* inconsistent.
All in all, one big circus. :100: 

Maestro Ochosi, thank you for the additional explanation.
