### ISSUE TITLE
Greybird not correctlly displayed on Maya calendar

### ISSUE THREAD

**Issue by sergioad** [shimmerproject/Greybird#76]
Hello @ochosi @satya164 a little Greybird bug was found on Maya calendar in Xubuntu 15.04 beta 1 maybe this could affect other apps too

![captura de pantalla_2015-02-26_16-38-41](https://cloud.githubusercontent.com/assets/5375145/6403965/cb8586c4-bdd8-11e4-87d7-2d085554c8cd.png)

Do you see the little square with not the correct texture on the CSDs? this is the bug, I hope see this issue fixed on the next Greybird's update :smile:

**Comment by ochosi** [comment]
Actually the "export" button also looks a bit broken. But to be honest I haven't worked on elementary support for Greybird in ages...
Feel free to open the GtkInspector (ctrl+alt+d) and check out what's wrong there!

**Comment by ochosi** [comment]
Additional note: could just as well be a bug in Maya, it's not really had a stable release afaik.

**Comment by sergioad** [comment]
@ochosi I will check

**Comment by ochosi** [comment]
I meant Ctrl+Shift+D when the application has focus.

Anyway, I installed the latest Maya in 15.04 and it works just fine...
![screenshot_2015-04-10_08-50-42](https://cloud.githubusercontent.com/assets/261436/7083154/c036ce0c-df5e-11e4-8848-81418c4ce9c5.png)

**Comment by sergioad** [comment]
Ok thank you so much, and what is up with Noise? now the theming works correctly too

**Comment by ochosi** [comment]
Ok good, closing this then.
