### ISSUE TITLE
Themeing Issues with some Xfce Panel Applets

### ISSUE THREAD

**Issue by tonypaulic** [shimmerproject/Greybird#77]
Some the current xfce4-panel applets (e.g. launchers, ApplicationsMenu, Clock, power-manager-plugin, actions plugin, mail watcher, etc) change background colour when the mouse hovers over the plugin. Others do not. The ones that I have found so far that do not change the background on mouse hover are:
- systemload
- fsguard
- systray
(not a complete list)

It would be nice if there was some consistency in that these would also exhibit the same mouse hover re-colouring effect.

**Comment by ochosi** [comment]
The systray (and likely those other plugins too) is a different widget, only GtkButtons get recolored on hover. This cannot be changed about the systray specifically, the other plugins could be ported I guess (but since I personally don't use them I dunno).
Either way, not a bug in Greybird.
