### ISSUE TITLE
greybird-gtk-theme: missing slider bar and incorrect checkbox color on Debian Jessie/Sid (Xfce 4.12)

### ISSUE THREAD

**Issue by braveheartleo** [shimmerproject/Greybird#78]
I believe a picture is worth a thousand words, and i hope this screenshot captures the issue at hand:

![screen](https://cloud.githubusercontent.com/assets/4935251/6655233/8b361c68-cb30-11e4-902f-1de30b08ae25.png)

For reference, here are the version numbers of the relevant packages
> xfce4-settings - 4.12.0-1
> libgtk2.0-0 - 2.24.25-3
> libgtk-3-0 - 3.14.5-1

I'm using git-master of greybird at bd6e6180cc

**Comment by ochosi** [comment]
That looks so wrong. Something must be seriously off there (and not the theme btw).

Either you have some stuff in your ~/.gtkrc or ~/.config/gtk-2.0/gtkrc or you're missing a theme engine or something.

**Comment by braveheartleo** [comment]
Hi,

> That looks so wrong. Something must be seriously off there (and not the theme btw).

It's quite an eyesore. I know that it must be something wrong or missing with my configuration but I don't know what.

I don't have `~/.gtkrc`, but I do have `~/.gtkrc-2.0` with the following content:

    style "xfdesktop-icon-view" {
    XfdesktopIconView::label-alpha = 0
    base[NORMAL] = "#000000"
    base[SELECTED] = "#71B9FF"
    base[ACTIVE] = "#71FFAD"
    fg[NORMAL] = "#ffffff"
    fg[SELECTED] = "#71B9FF"
    fg[ACTIVE] = "#71FFAD" }
    widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"`

There is no `~/.config/gtk-2.0/gtkrc` in my home dir.

Regarding theme engines, I understand that greybird requires `gtk2-engine-murrine` and `gtk2-engine-pixbuf`, and they are both installed. Here are their corresponding versions:

    gtk2-engines-murrine:amd64/unstable 0.98.1.1-5 uptodate
    gtk2-engines-murrine:i386/unstable 0.98.1.1-5 uptodate
    gtk2-engines-pixbuf:amd64/unstable 2.24.25-3 uptodate
    gtk2-engines-pixbuf:i386/unstable 2.24.25-3 uptodate

Could there be something else that I'm missing?

**Comment by ochosi** [comment]
Frankly, many aspects of that window seem to suggest you're not even using Greybird because it looks so different. That gtkrc is fine, it shouldn't conflict with the settings dialog. The packages and their versions seem fine. Do you have an older version of the theme in ~./themes or /usr/share/themes?

![screenshot_2015-03-15_13-36-10](https://cloud.githubusercontent.com/assets/261436/6655986/419612ba-cb18-11e4-895d-289a91c6005c.png)

**Comment by braveheartleo** [comment]
> Frankly, many aspects of that window seem to suggest you're not even using Greybird because it looks so different.

That seems highly unlikely because I git-cloned this repository.

> Do you have an older version of the theme in ~./themes or /usr/share/themes?

Debian doesn't have greybird in its repositories. However, for troubleshooting purposes, I downloaded a copy of `greybird-gtk-theme` from Ubuntu's repos here: http://packages.ubuntu.com/vivid/greybird-gtk-theme (I use the vivid release because Gtk3 there is at 3.14, same as Debian's).

And even if using the theme that came with the Ubuntu package, I still end up with the same issue.

Also, there are no further indications related to the theme in `~/.xsession-errors` that may tell I'm missing some engine or something else.

**Comment by ochosi** [comment]
I thought it was available on Debian in a shimmer-themes package, but I might be wrong.

Anyway, I honestly have no clue what's going on there – using the version from Vivid is ok – I'm pretty sure though that it has nothing to do with the theme but is a local problem of yours.

**Comment by braveheartleo** [comment]
> I thought it was available on Debian in a shimmer-themes package, but I might be wrong.

Nope, no `shimmer-themes` package as well.

Hmm, one question though. Would you happen to be using Ubuntu, or any variants of it?

**Comment by ochosi** [comment]
Yup, I'm currently Xubuntu Project Lead (and also using Xubuntu).

**Comment by braveheartleo** [comment]
I created another user in my system so that I have a clean profile and rule out any chance that it might be due to any mis-configured local data. Still, I'm experiencing the issue with this new user the same as in the first post.

Before Debian, I was using Xubuntu 14.04 that came with Xfce 4.10. Even then, I was already using git-master of greybird, but replacing the gtk-3.0 directory with the one suitable for Gtk+ 3.10. Then Xfce 4.12 came out and I upgraded to it via PPAs. Still, I got no problems with greybird-master and Xfce 4.12, until switching over to Debian.

I take it that greybird does not receive much testing on the Debian front, and that it is primarily a Xubuntu Gtk theme?

**Comment by ochosi** [comment]
Thanks! :)
I'm pretty sure that it receives testing on Debian as well, I'll ask around...

**Comment by braveheartleo** [comment]
I'm rolling with Debian Sid (unstable) btw, which is at the moment frozen due to Jessie.

I tried updating the gdk-pixbuf image loader cache, because it is the pixmap engine that is responsible for loading the image files used by the theme (and which I have observed have been missing from certain parts of the DE like Thunar's un-themed breadcrumbs and side bar:
![screen01](https://cloud.githubusercontent.com/assets/4935251/6685466/ec6dd7e6-ccd4-11e4-9a36-57ac166a49ea.png)

and the missing slider bar), but no dice.

I'm still hunting down where the issue might be. If you could give some other hints regarding this it would really be helpful.

**Comment by braveheartleo** [comment]
I wish to add that I do not observe the issue in Gtk+ 3.xx, only in Gtk+ 2.xx. The following is Gtk+ Widget Factory v3.14.5:
![screen](https://cloud.githubusercontent.com/assets/4935251/6693737/185e3f0e-cd10-11e4-9521-f2477a816313.png)

**Comment by braveheartleo** [comment]
I tried Xubuntu 15.04 and from there greybird-master works like a charm. None of the issues stated above were found in Xubuntu. I think this can be attributed to how differently the packages are built between Debian and Ubuntu.

This issue can now be closed, as greybird is primarily a (X)ubuntu theme.
