### ISSUE TITLE
greybird-gtk-theme: some minor graphical issues with Gtk+ 3.14 apps on Debian Jessie/Sid (Xfce 4.12)

### ISSUE THREAD

**Issue by braveheartleo** [shimmerproject/Greybird#79]
The bottom edge is cut on the close button, but not on the others:
![screen05](https://cloud.githubusercontent.com/assets/4935251/6655308/8121e6fe-cb34-11e4-9bdc-079f11467df7.png)

The buttons are stretched at the bottom of this message dialog:
![screen02](https://cloud.githubusercontent.com/assets/4935251/6655289/6ee2db16-cb33-11e4-86cf-3d8ea7affad1.png)

The tab bar has a background when there should be none:
![screen03](https://cloud.githubusercontent.com/assets/4935251/6655294/d554ca62-cb33-11e4-9044-f3910ce4ce6a.png)

The X (close) button is rendered differently than the minimize and maximize buttons on this window:
![screen04](https://cloud.githubusercontent.com/assets/4935251/6655305/2860a852-cb34-11e4-9603-13cfb4fd38f0.png)

I'm using git-master of greybird at bd6e6180

I will update this report if I notice any other graphical anomalies.

**Comment by ochosi** [comment]
The first issue I can't reproduce (see screenshot).
![screenshot_2015-03-15_12-48-53](https://cloud.githubusercontent.com/assets/261436/6655857/b51406f4-cb11-11e4-9db8-a9f5f2ff319a.png)


All the other things you mentioned are expected and actually changes in Gtk3, not the theme (stretched buttons, tab bar background etc.) The close button comes from your icon theme (seemingly Faenza).

**Comment by braveheartleo** [comment]
Hi,

> All the other things you mentioned are expected and actually changes in Gtk3, not the theme (stretched buttons, tab bar background etc.)

Thanks for that information. Gtk+ 3.xx sure is undergoing some changes, for better or worse, with each new release.

> The close button comes from your icon theme (seemingly Faenza).

Indeed, I'm using `faenza-xfce`. I just find it odd that the minimize and maximize button icons are different than the close button icon. Is there any way to prevent this behavior though? I'm not well-versed in gtk themes.

> The first issue I can't reproduce (see screenshot).

Hmm, I guess it's just some minor glitch in my chosen configuration. It's not really a deal breaker.

**Comment by ochosi** [comment]
> Indeed, I'm using faenza-xfce. I just find it odd that the minimize and maximize button icons are different than the close button icon. Is there any way to prevent this behavior though? I'm not well-versed in gtk themes.

Faenza-xfce – you mean this old beast? https://github.com/shimmerproject/Faenza-xfce

Either way, I think the easiest way for you to fix that is to replace the window-close-symbolic icon with the one from elementary-xfce, that one pretty much matches Greybird.

**Comment by braveheartleo** [comment]
Yup, that's the one, modified to inherit Faenza-Cupertino so that I get those nice blue folder icons with it. ^_^

I wish that icon pack could be updated and new icons created for it, though.

> Either way, I think the easiest way for you to fix that is to replace the window-close-symbolic icon with the one from elementary-xfce, that one pretty much matches Greybird.

Thanks for the hint. I also have a git-cloned copy of elementary-xfce, switching back and forth between it and Faenza.

A quick request regarding elementary-xfce icons: since introducing a bright theme for xfce4-notifyd, the notification icons that come with the icon pack do not have dark icons that could go along with theme. Are there any plans on creating dark notification icons for this?

**Comment by ochosi** [comment]
Faenza is already a bit dusty tbh, no updates in a loooong time.

Yeah, either I'll create dark notification icons (although that'll result in yet another subtheme and I'm not sure which other themes it should inherit and how to name it) or I'll soon start porting xfce4-notifyd to Gtk3 so that symbolic icons can be used instead (which will automatically be recolored correctly).

**Comment by braveheartleo** [comment]
Thanks for that great news. I think this issue can now be closed.
