### ISSUE TITLE
Unity Top Panel Menu

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#87]
I think it will be better to make active/selected/hover effect on Unity Top Panel Menu items the same (blue, and not transparent) as regular application menubar items as seen together (collated) in the screenshot below.
![screenshot from 2015-04-28 01 00 23](https://cloud.githubusercontent.com/assets/6375934/7359160/0bc81022-ed44-11e4-9426-22fcf10eae75.png)

**Comment by ochosi** [comment]
Hi, well I don't use Unity so I'm not actively maintaining the Unity-part of the theme. I don't remember who exactly contributed that part, but I'm personally not going to fiddle with it since I can't/won't test it.
Sorry, cheers!

**Comment by Sadi58** [comment]
Unfortunately, I'm just a user, and not a themer.
 But I can do some copy & paste jobs ;-)
So "borrowing" some code from the menubar section in "gtk-widgets.css" (as well as another theme which has similar "menubar" styling in Unity Top Panel) I came up with this, which is very close, except lacking a little space at the top and boldish (or shadowy?) text color:
```
.unity-panel.menuitem,
.unity-panel .menuitem {
    border-width: 1px;
    color: @menubar_fg_color;
}

.unity-panel.menubar.menuitem:hover,
.unity-panel.menubar .menuitem *:hover {
    border-radius: 5px 5px 0px 0px;
    border-bottom: none;
    border-color: shade(@theme_selected_bg_color, 0.8);
    background-image: linear-gradient(to bottom,
                                      shade(@theme_selected_bg_color, 1.2),
                                      shade(@theme_selected_bg_color, 1.0)
                                      );

    color: @theme_selected_fg_color;
}
```

**Comment by ochosi** [comment]
As I have recently rebased Greybird and also re-done the Unity part (based on what the Ubuntu devs do in the Radiance/Ambiance themes) I was wondering whether this part looks better now (I still don't have Unity here :))

**Comment by Sadi58** [comment]
Thanks, I see that hover and selection highlight for menu bars in app windows is also transparent now - consistent with Unity top panel.
