### ISSUE TITLE
checkboxes, radiobuttons, etc.

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#88]
I wonder if it's intentional to have those checkboxes, radiobuttons, etc. that are not selected/enabled completely invisible, which leaves the user a bit in the dark that those items are selectable - Ubuntu 15.04, GTK 3.14.
The screenshot below shows Transmission's View menu as via Greybird and Vertex.
![greybird-buttons](https://cloud.githubusercontent.com/assets/6375934/7366429/d959729a-eda0-11e4-94cf-416fdd1b2975.png)

**Comment by fitojb** [comment]
I don’t think that this is an issue. That’s the way menus have always behaved. Vertex is a recent exception to the norm.

**Comment by ochosi** [comment]
Yup, that look is intended ;)
