### ISSUE TITLE
Instabilities (temporary freeze and black screen)

### ISSUE THREAD

**Issue by hartwork** [shimmerproject/Greybird#89]
Hi!

I'm using Xorg 1.17.1, Xfwm 4.12.2 and Greybird 1.5.3. When using Greybird for window decorations (titlebar and frame) I experience trouble that I do not experience with other decorators, e.g. Zukitwo works fine.
The symptoms are temporary freeze and a black screen for a moment when snapping windows into corners (e.g. dragging the window with the mouse cursor to the left side of the screen makes the window take the left half of the screen, the upper left corner would make it use the upper left fourth and so on). It happens with both Thunderbird and Audacious.
I would love to switch back to Greybird.

Best, Sebastian

**Comment by ochosi** [comment]
Frankly I have no clue what could be causing this. It's possible that it's some instability in the theme engines used by Greybird (murrine and pixbuf), you could check which ones Zukitwo uses (I think it at least uses murrine) to see whether that fixes the problem.

Either way, this is definitely not a widespread issue, and I see little to no reason how this could be the theme's fault.

**Comment by hartwork** [comment]
I have no idea how it could be the themes fault either. I just know that It happens with greybird and no other theme so far. I could make a video demonstrating the issue but I guess we'd still be wondering after.

**Comment by ochosi** [comment]
Indeed. The only thing you can check are your logs. Either dmesg or the xorg log or even the session log (the latter might be in various places, depending on what manages your session how).
