### ISSUE TITLE
Nautilus sidebar symbolic icons

### ISSUE THREAD

**Issue by Sadi58** [shimmerproject/Greybird#91]
I think there's a problem with the way Greybird displays the symbolic icon for Recent items in Nautilus Sidebar as can be seen in the screenshot below showing Nautilus window under Greybird (top) and Vertex-Light (bottom) themes.
![nautilus-recent_greybird-issue](https://cloud.githubusercontent.com/assets/6375934/7587654/985d6e6a-f8c0-11e4-8739-d7dbc258ec4b.jpg)

**Comment by ochosi** [comment]
Hey, I don't use nautilus so I don't know. Could you check with gtkinspector? (Hit Ctrl+Shift+D with the application you want to inspect having focus)

**Comment by Sadi58** [comment]
Sorry, this is the first time I use gtkinspector; what should I look for?

**Comment by ochosi** [comment]
Try to find the recent item and then you can look e.g. in the "CSS Classes" tab, or the "properties" or the "style properties" tab and compare them to other items in that sidebar. Then spot the difference.

**Comment by Sadi58** [comment]
I could only find NautilusWindow > GtkPlacesSidebar under Objects but nothing more, unfortunately.

**Comment by Sadi58** [comment]
BTW I've also just noticed that this is an inconsistent behavior: although I see this issue with Nitrux icon theme, I see Greybird showing normal icon with Numix-Circle-Light icon theme...

**Comment by ochosi** [comment]
Phu, sorry, I'm still lost :)

If you find any good leads on how to fix this I'm all ears though!

**Comment by Sadi58** [comment]
Actually, I now think we should close this issue assuming that all it takes is creating yet another symlink which doesn't exist in Nitrux icon theme but which exists in Numix-Circle icon theme.

**Comment by ochosi** [comment]
Alright, thanks!

**Comment by Sadi58** [comment]
I now have a similar problem with the "Browse Network" icon -- using color app icon in Nautilus sidebar when using Numix icon theme, actually Numix-Circle-Light, instead of a monocolor one :-(

It looks like a puzzle:

Greybird GTK theme + Nitrux icon theme = no problem
Greybird GTK theme + Numix icon theme = problem
Other GTK theme + Numix icon theme = no problem

I noticed that Nitrux icon theme has 5 *network*.svg images in its "/places/16/" subfolder, one of which (all showing the same image) is used in Nautilus sidebar, while Numix has only one in its relevant subfolder: "network-workgroup-symbolic.svg".
However, creating symlinks for all those names in Nitrux icon theme, and even duplicating them with a *-symbolic" suffix, which was not used in Nitrux, didn't solve the problem (even after refreshing the icon cache file and restarting nautilus).

**Comment by ochosi** [comment]
Can you still reproduce this issue with Greybird 3.20.x and Gtk3.20?

**Comment by Sadi58** [comment]
No, this problem no longer exists! Thanks...
