### ISSUE TITLE
Geary message listview background color (Greybird/Numix)

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/Greybird#93]
In Geary, the message listview is no longer white, and does not look too great in Greybird or Numix.  This is a change introduced in Geary 0.10.  There are a few themes where this still looks acceptable, Adwaita being the best.
![screenshot_2015-06-24_07-21-58](https://cloud.githubusercontent.com/assets/1894517/8328812/fd827f40-1a41-11e5-8705-f5c5f38e191b.png)

**Comment by ochosi** [comment]
Indeed, Geary 0.8 looks pretty much ok (which also makes me wonder whether it's really the theme's fault...). However with 0.8 I get a weird mixture between symbolic and colored icons in the sidebar, no idea why that is.

I'll check again with 0.10 soonish.
