### ISSUE TITLE
Greybird not respect GTK_RELIEF_NONE on GtkHeaderbar

### ISSUE THREAD

**Issue by matiasdelellis** [shimmerproject/Greybird#94]
Hi,
Note this when I started to porting Pragha to GtkHeaderBar (But as I change some classes by hand, ignore it), and just now check it using a standard program.

How to reproduce?
> Open gtk3-icon-browser
> Launch inspector.
> Select a button of of HeaderBar. I.g. Symbolic or search button.
> Properties -> relief.
> Change it to GTK_RELIEF_NONE.

What do I expect? The buttons are flat.
What do I get ?. Buttons are equal.. :(

Comparisons are odious, but here the same, with greybird and adwaita. Symbolic and search button with GTK_RELIEF_NONE

![greybird-set-relief_none](https://cloud.githubusercontent.com/assets/733715/8488523/8915dc48-20e9-11e5-9820-56f0439da76f.png)
![adwaita-set-relief_none](https://cloud.githubusercontent.com/assets/733715/8488528/8da185d2-20e9-11e5-9fa2-ad595ba43d4c.png)

Regards,

**Comment by ochosi** [comment]
Hey Matias!
They're actually not the same. The GTK_RELIEF_NONE buttons don't have any white inset border, so they look just flat. I guess I can fix that though.

**Comment by matiasdelellis** [comment]
Wow..
Thanks Simon, :grinning:
