### ISSUE TITLE
Use blured shadow on xfdesktop4

### ISSUE THREAD

**Issue by matiasdelellis** [shimmerproject/Greybird#99]
Hi Simon,
A small proposal: See image to see diferences:
![change-shadows](https://cloud.githubusercontent.com/assets/733715/9050694/332264a8-3a27-11e5-88cb-e08d9bfac354.png)

* The first rows is master.
* The second row is adding the option:
 *  XfdesktopIconView::shadow-blur-radius = 2

IMHO looks much better.. :grinning: 

These is te propoced on this bug, but also hope that you consider the third row that is adding the options:
  * XfdesktopIconView::ellipsize-icon-labels = 0
  * XfdesktopIconView::selected-label-alpha = 0

This removes the shadows and prevents the text look different when selecting icons, that can be a bit annoying.

Regards,

**Comment by ochosi** [comment]
Hey Matias,

ah right, I forgot about the blur option. Haven't touched the xfdesktop theming in a while, but I'll add that one in.

About the selected-label-alpha: IMO it looks more consistent with Thunar (and all GtkIconViews) if there is a selection box around the label. At least for me, the desktop is just another folder displayed at the bottom of it all.

And re: ellipsizing: I haven't tried that (I don't have any icons on my desktop), but what happens with the overflow and the grid? Does it move icons outside of the grid or do they overlay each other when a folder or file has a *really* long name?

**Comment by matiasdelellis** [comment]
> ah right, I forgot about the blur option. Haven't touched the xfdesktop theming in a while, but I'll add that one in.

Thanks.

> About the selected-label-alpha: IMO it looks more consistent with Thunar (and all GtkIconViews) if there is a selection box around the label. At least for me, the desktop is just another folder displayed at the bottom of it all.

Ok.. Matter of taste, and you are the designer!. :wink:

> And re: ellipsizing: I haven't tried that (I don't have any icons on my desktop), but what happens with the overflow and the grid? Does it move icons outside of the grid or do they overlay each other when a folder or file has a really long name?

No.. The grid is fixed, and if the text is very long, it can overlap the icon that is below.. However, except for the dynamic grid, in this way it is shown in thunar.

Long name are very rare, and always you can move them to make look correctly

Thanks for the change,
It looks good!.

**Comment by matiasdelellis** [comment]
>> And re: ellipsizing: I haven't tried that (I don't have any icons on my desktop), but what happens with the overflow and the grid? Does it move icons outside of the grid or do they overlay each other when a folder or file has a really long name?

> No.. The grid is fixed, and if the text is very long, it can overlap the icon that is below.. However, except for the dynamic grid, in this way it is shown in thunar.

>Long name are very rare, and always you can move them to make look correctly

Just I did a couple of tests. Forget the ellipse. =) It does not add much and with the changes you did'm very happy.

Thanks for everything,
If you want, close the issue.

Regards,
Matias.

**Comment by ochosi** [comment]
Ok perfect, thanks for your attention to detail, Matias!

**Comment by ochosi** [comment]
Hmpf, noticed that with shadow-blur-radius=2 I get oversized selection bubbles (on the y axis). Seems like something goes wrong there with the calculation, so I'm not sure whether I shouldn't revert that...

**Comment by matiasdelellis** [comment]
Hi, has a bug on 4.12 that is fixed on 4.12.1 or 4.12.2

That version has xubuntu now..??

**Comment by ochosi** [comment]
Oh, you're right! 15.04 still has 4.12.0 but in Wily everything is perfect. Thanks again!
